### ISSUE TITLE
Display Parse Time

### ISSUE THREAD

**Issue by jogibear9988** [fkling/astexplorer#103]
I'm looking to use a Javascript Parser to impl. smth. like IQueryable in Javascript. For this I need to find a high performant JS Parser. Would it be possible that you show the Parse time somewhere?

**Comment by hzoo** [comment]
Would be cool. esprima has some stats (although I don't think it's updated) http://esprima.org/test/compare.html

**Comment by fkling** [comment]
Yeah, we can do that. I'm currently working on rewriting the internals and will add this.

**Comment by hzoo** [comment]
Nice, the first parse is like ~100ms and then ~2ms

**Comment by fkling** [comment]
@hzoo: yeah, I realized later that the first call includes loading the parser.

**Comment by hzoo** [comment]
Could we add a time for transforms too?
