### ISSUE TITLE
Selected Parser not persisted upon save

### ISSUE THREAD

**Issue by DrewML** [fkling/astexplorer#115]
To start with, thanks so much for the excellent tool!

Reading https://github.com/fkling/astexplorer/issues/67#issuecomment-162856324, it leads me to believe that the expected behavior currently is that the selected parser should be persisted when you `Save` a transform. That does not seem to be working for me currently with new transforms I create on the site.

Was there a recent regression, or am I possibly just overlooking something?

I should note that, the selected parser does still show for the example that was linked in #67 (http://astexplorer.net/#/np0DfVT78g).

**Comment by RReverser** [comment]
@DrewML The link you provided opens with PostCSS parser selected. Which one would you expect instead?

**Comment by fkling** [comment]
I assume what happens is that you selected a parser that is different from the transform's default parser. If you have a transform, then the transform's default parser will always selected, even if you change the parser. This isn't really documented anywhere, so the confusion is understandable.

If this is indeed the problem, we can discuss if this behavior should be changed. E.g. this behavior would make sense for transformers which can work with multiple parsers.

**Comment by DrewML** [comment]
@RReverser Thanks for looking! That link I provided at the end was just an example showing that a parser setting does persist for _some_ saved transforms. I probably should have provided an example of one where it didn't work as well :)

@fkling You nailed it - that's definitely the scenario. [Here is an example transform](https://astexplorer.net/#/ECeWqibQcR/15).

Originally I was changing the parser itself because I didn't think `recast` played well with the spec for class properties. However, I didn't realize that I could change the parser `recast` uses to `babel-core`. Now that I've found that setting, this issue isn't much of a problem for me, since the `recast` settings _do_ persist upon save

**Comment by fkling** [comment]
> since the recast settings do persist upon save

Only locally though ;) Parser settings are not stored in Parse yet. I guess we should do that to at some point. Right now, the parser settings are only accessible from within each parser. I want to refactor how parser settings work soon, so that they can be passed in from the outside (e.g. an API). Then it would also be easier to save the settings with the code snippet.

**Comment by DrewML** [comment]
Cool. Let me know if there is anything I can do to help/contribute.

**Comment by fkling** [comment]
Parser settings are now saved, so this shouldn't be an issue anymore!

**Comment by DrewML** [comment]
You rock @fkling - thank you!
