### ISSUE TITLE
Allow selecting dependent transforms

### ISSUE THREAD

**Issue by STRML** [fkling/astexplorer#120]
#112 pulled out all other Babel plugins when transforming input code. This breaks astexplorer on e.g. Flow syntax transforms, as Babel can't parse the AST without the parser plugin.

As a simple stopgap I think it makes sense to include all parser plugins, but it would be even better if a dialog allowed selection of which core plugins to use.

**Comment by fkling** [comment]
Uh :-/ It seems we should include all syntax plugins but no transform plugins?

**Comment by STRML** [comment]
Yeah, that seems safe enough for now. I'm working on a PR.
