### ISSUE TITLE
transform for doing auto-fixes with ESLint?

### ISSUE THREAD

**Issue by nmn** [fkling/astexplorer#123]
Would it be possible to add a second mode for Eslint that just runs the eslint fix on the source code.

Being able to write Eslint plugins in ASTExplorer is awesome. This would make it possible to write functions to fix some of the issues automatically.

**Comment by fkling** [comment]
I don't know how autofixing works. Do we need a second mode or can we just enable this? How to plugins signal that it can autofix stuff?

**Comment by RReverser** [comment]
@fkling I guess the difference @nmn is asking for is that autofixing actually transforms the source code (similarly to jscodeshift / babel / etc.), while current ESLint mode uses output area for showing errors. So yeah, I guess we'll need some separate mode for that.

**Comment by hzoo** [comment]
@fkling plugin rules can implement a `fix` function in the reporter

**Comment by fkling** [comment]
@RReverser: Doh, that makes sense. I guess it's time to implement custom output for transform tools. Need to get the redux stuff in first though.

**Comment by gyandeeps** [comment]
I will work on this and sen a Pull request.

**Comment by jamiter** [comment]
@gyandeeps, any luck so far?

**Comment by gyandeeps** [comment]
There is no direct fix API available as of right now. I can go around the library to copy eslint's small fix function and run that to get the fixes out. But we are planning to expose that in near future that why I did not start working on this.

Also we need some sort of window on UI so that we can show fixed code as well as lint issues. Which I am not sure what the plan is.

**Comment by fkling** [comment]
> Which I am not sure what the plan is.

I was thinking every tool can have a method that allows it to render a custom component as output. So eslint could render both. There might be better solutions though. Happy about any suggestions 😃

**Comment by gyandeeps** [comment]
Sounds good to me @fkling ... What your thoughts on ESLint fix approach?
Should copy the function to make it work? I am on ESLint org and we have not started work on exposing fix api through linter interface.

**Comment by hzoo** [comment]
Could have 2 tabs, but yeah rendering a component would be nice

**Comment by gyandeeps** [comment]
**UPDATE:** We at ESLint have made some changes around exposing Linter API which has auto fixing in it (I have done both PR and waiting on the last one to merge). After ESLint 4.0 is released then i will work on this issue.

**Comment by gyandeeps** [comment]
**UPDATE:**
I have finished up all the work on eslint to get the fix functionality working.
It will be released with `4.1.0` in around weeks time..

TODO:

* Merge #241 as it introduces ESLint 4.
* Come up with design on where the fix code will sit.
* Do we need an option to turn on/off fix while the lint errors are still shown? or is it always on.

**Comment by gyandeeps** [comment]
Alright, ESLint `4.1.1` has been released and now we should be able to implement it here.
I have already implemented it on ESLint demo site: http://eslint.org/demo/

Now we need to answer the questions listed above :point_up:

**Comment by gyandeeps** [comment]
ping @fkling @RReverser 👆

**Comment by jridgewell** [comment]
This would be great to have.
