### ISSUE TITLE
Cannot build package with Node v6

### ISSUE THREAD

**Issue by vtrushin** [fkling/astexplorer#137]
I'm using node v6.0.0. When I try to build your project clone, get an error: "ERROR in Path must be a string. Received undefined"

**Comment by hzoo** [comment]
It's a node 6 issue (use v5) - I had the same [issue](https://twitter.com/left_pad/status/741383550583328769)

**Comment by fkling** [comment]
Yeah, either astexplorer itself or some dependency doesn't work with es6. Haven't figured out which one yet.

**Comment by thorn0** [comment]
When I'm trying to build it on Node 6.5, `uglify-loader` fails to process the `jscodeshift` module, which contains ES2015 parts unsupported by Uglify (classes, enhanced object literals).
