### ISSUE TITLE
JSON view is broken

### ISSUE THREAD

**Issue by JamesHenry** [fkling/astexplorer#141]
On astexplorer.net, it's no longer possible to access the JSON view of the AST because it is throwing an error when clicking on it:

![unspecified-1](https://cloud.githubusercontent.com/assets/900523/17533598/6bf6be52-5e7d-11e6-85f7-a799f01262c4.png)

**Comment by fkling** [comment]
That must be when I switched to react v15

**Comment by JamesHenry** [comment]
React verkackt 😄
