### ISSUE TITLE
Please give feedback about using gists as storage

### ISSUE THREAD

**Issue by fkling** [fkling/astexplorer#142]
I have been thinking about this on and off, trying to find good arguments for and against using [**gists**](https://gist.github.com/) as the backing storage for astexplorer (this is also beause of parse shutting down ( #94 )).

Here are some features gists offers:
- If authenticated, gists are owned by the authenticated user
- Gists are versioned (if authenticated)
- Gists can be forked
- Gists can be public or “secret” (everybody can access a gist if they have its ID)

So gists already implement some features that astexplorer has (versioning and forking) or is on the whishlist (user accounts).

In addition to those features other benefits of using gists would be:
- Can be updated and accessed independently of astexplorer (would allow integration with other tools)
- No data lock-in to astexplorer, gists can be shared separately

One limitation is that, at least as far as I know, only the owner of a gist can create new revisions. Currently everybody can create new revisions for a saved snippet in astexplorer. However, I personally see this limitation positively. If one wants to adapt another gist, they would have to fork it, which provides a clear history of who did and changed what.

A **disadvantage** of moving to gists would be the dependency on GitHub. However I feel like if GitHub every disappears or discontinuous this service, we would have bigger problems than astexplorer not working.

What do you think? Anything that I have overlooked or concerns you have?

---

**Q: What happens to the existing data?**
**A:** The existing data would be moved over to secret gists, owned by a new user (e.g. astexplorer). We would redirect the existing IDs to the new gist IDs, which would still require a server, but won’t require us to run our own database.
Nobody else could create new versions of these gists, but they could be forked.

**Q: Do I need to be logged into GitHub to save code and transforms?**
**A:** Most likely. I assume those who want to save already have GitHub accounts. We could think about adding a way to save anonymous gists though. Personally I see the authentication positively.

**Q: Will GitHub API rate limits be a problem for astexplorer?**
**A:** Not at astexplorer’s current scale. Also, if you are authenticated with GitHub, all API requests would account against your rate limit.

**Q: Does GitHub allow something like this?**
**A:** I hope so? Let me know if I’m wrong 😟 

---

Tagging people who might have an opinion: @RReverser, @hzoo, @TimothyGu

**Comment by hzoo** [comment]
This sounds great to me! I think it is fine to have separate versions per user as well.

**Comment by TimothyGu** [comment]
The general idea sounds good. Support for forking is especially cool.

About how many entries are currently included in the Parse database?

**Comment by fkling** [comment]
@TimothyGu: According to the parse dashboard, there are ~2360 saved snippets and ~5770 revisions.

**Comment by Saturate** [comment]
The dependency on GitHub, is fine... it they shut down, it's a rewrite, but that's pretty unlikely.

**Comment by fkling** [comment]
See #184 for new information.
