### ISSUE TITLE
Generate ast-building code from given source

### ISSUE THREAD

**Issue by fab1an** [fkling/astexplorer#146]
When I generated code in plugins I often have to look what the various elements are called like and what arguments they expect. Also the "reverse" chaining is not intuitive at times.

I'd be cool if I could input the source I want:

``` javascript
this.emit.bind(this, 'myArgument')
```

and get the code needed to generate it:

``` javascript
import * as t from "babel-types";

t.callExpression(
    t.memberExpression(
        t.memberExpression(
            t.Identifier("this"),
            t.Identifier("emit")
        ),
        t.Identifier("bind")
    ),
    [
        t.thisExpression(),
        t.StringLiteral("myArgument")
    ]
)
```

**Comment by hzoo** [comment]
you can use babel-template: https://github.com/babel/babel/tree/master/packages/babel-template, also included in the plugin with `export default function ({types: t, template}) {`

**Comment by wmhilton** [comment]
Squeal! I was just about to invent something like `babel-template`! @hzoo this is so exciting!

**Comment by DanielSWolf** [comment]
It would be very helpful if this feature were included in AST explorer. It already has a "Tree" tab and a "JSON" tab. A tab named "Creation code" (or something like that) would be really handy.

I just spent half an hour manually transforming this code:

```js
if (typeof getRedefinition === 'undefined') {
  (typeof window !== 'undefined' ? window : global).getRedefinition = function (value) {
    return value;
  };
}
```
into that:

```js
t.ifStatement(
  t.binaryExpression(
    '===',
    t.unaryExpression('typeof', t.identifier('getRedefinition')),
    t.stringLiteral('undefined')
  ),
  t.blockStatement(
    [
      t.expressionStatement(
        t.assignmentExpression(
          '=',
          t.memberExpression(
            t.conditionalExpression(
              t.binaryExpression(
                '!==',
                t.unaryExpression('typeof', t.identifier('window')),
                t.stringLiteral('undefined')
              ),
              t.identifier('window'),
              t.identifier('global')
            ),
            t.identifier('getRedefinition')
          ),
          t.functionExpression(
            null,
            [t.identifier('value')],
            t.blockStatement(
              [
                t.returnStatement(t.identifier('value')),
              ]
            )
          )
        )
      ),
    ]
  )
);
```

**Comment by RReverser** [comment]
@DanielSWolf Why do you need that long nested expression instead of using `babel-template` or `estemplate` as suggested above?

**Comment by fkling** [comment]
If someone wants to contribute that I'm happy to review it!

**Comment by DanielSWolf** [comment]
@RReverser Thanks for pointing me at `babel-template` (again). I must confess that when I first followed the link in @hzoo's comment, I completely misunderstood what that library does.

I'm going to replace my "long nested expression" with a short and readable `babel-template` expression and not look back! 😄

There are so many great features to Babel if one knows where to look!

**Comment by hzoo** [comment]
We could do a better job of explaining that and documenting but that may be hard to do.. I might even suggest using template in the example plugin for Babel, but not sure if that makes it too complicated. Otherwise I think this can be closed?

**Comment by DanielSWolf** [comment]
I agree that this issue can be closed.
