### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by brigand** [fkling/astexplorer#159]
I'm getting a mostly blank page with this in the console on http://astexplorer.net/

![image](https://cloud.githubusercontent.com/assets/936069/19980149/30d19556-a1ba-11e6-960b-c0bbe8fd72e3.png)

**Comment by fkling** [comment]
Yep. I rebuilt the site, but it's basically the same error. I don't know why this is happening since the file exists (hash changed since the last rebuild):

https://github.com/fkling/astexplorer/blob/ae099677d3d08f6ee57d92f3d9b13e40e91f6445/vendor-1ea330d5574f59ce03f8.js

Any ideas?

**Comment by fkling** [comment]
I don't see how this is an issue from our side, so I contacted GitHub support. Sorry for the inconvenience!

**Comment by captbaritone** [comment]
Interesting, it works on Rawgit: http://rawgit.com/fkling/astexplorer/gh-pages/index.html that does seem to confirm that the files are present.

**Comment by fkling** [comment]
@captbaritone, thanks, I didn't know about that! I'm (temporarily) loading the initial files from there instead, which makes the site available again.

**Comment by brigand** [comment]
Thanks for the quick fix and the wonderful tool 😄

**Comment by fkling** [comment]
Got a response from GitHub:

> Thanks for reaching out! We recently upgraded to Jekyll v3.3, which ignores vendored files. Since you're not using Jekyll, you can add a `.nojekyll` file to the root of your repository to disable Jekyll from building your site. Once you do that, your site should build correctly with all of your files.

For reference, here is the blog post with the upgrade announcement: https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3 .

And it worked. Looks like Jekyll is not only ignoring the *folder* `vendor` though...
