### ISSUE TITLE
unknown: false == true

### ISSUE THREAD

**Issue by brigand** [fkling/astexplorer#170]
Getting a weird error message: "unknown: false == true"

[#/jZLC75XjGP/1](http://astexplorer.net/#/jZLC75XjGP/1)

it works if I change the `assert(1, 2, 3)` to `1 && assert(1, 2, 3)`.

The plugin works on the command line (changing `export default` to `module.exports =`). [Full repro.](https://gist.github.com/brigand/ef0a1e6b074f047637c597c49a1dd1f2)

**Comment by hzoo** [comment]
There's an issue with the way I setup recast such that if you have a newline at the end of the input code (top left) there's this bug. Remove the newline at the end and it should work?

**Comment by brigand** [comment]
Yep, that seems to fix it.

**Comment by fkling** [comment]
Are you going to fix this on your side @hzoo or should we just always trim trailing whitespace from code?

**Comment by hzoo** [comment]
Going to have to look into it more so maybe doing that for now is better

**Comment by hzoo** [comment]
Got a few reports of this so maybe we should just do that ^ (trim whitespace)

**Comment by fkling** [comment]
I think this works now.
