### ISSUE TITLE
✨ Thanks for making this ✨

### ISSUE THREAD

**Issue by koddsson** [fkling/astexplorer#180]
Hey there @fkling (and contributors)!

Not a real issue here. Just wanted to take the time to thank you for this amazing tool! I really, really, really like it and I use it a lot for writing codemods.

![](https://m.popkey.co/eae3e9/L9KlL.gif)

❤️❤️❤️

**Comment by fkling** [comment]
Thank you 😃  Much appreciated!

**Comment by fkling** [comment]
Closing this now 😉
