### ISSUE TITLE
Transformer output is reversed

### ISSUE THREAD

**Issue by montogeek** [fkling/astexplorer#188]
Hi!

![image](https://cloud.githubusercontent.com/assets/1002461/22175645/31357422-dfc7-11e6-8462-75779e253189.png)

I am getting the transformer output reversed in each line, is this ok?
Here is the link to the code: https://astexplorer.net/#/d0MF2QGa4Z

**Comment by SergioCrisostomo** [comment]
@montogeek yes, that is the default codemod demo from jscodeshift. 

Turn on the editor here:

<img width="370" alt="skarmavbild 2017-01-21 kl 19 03 36" src="https://cloud.githubusercontent.com/assets/5614559/22176501/7fabcb52-e00c-11e6-94cd-4af13031784a.png">

and then you will the the `.reverse()` in the codemod inverting the names:

<img width="565" alt="skarmavbild 2017-01-21 kl 19 03 49" src="https://cloud.githubusercontent.com/assets/5614559/22176504/9b91f15c-e00c-11e6-821d-34c749d589e5.png">

**Comment by montogeek** [comment]
Oh, thanks!
