### ISSUE TITLE
Can't handle Flow's <*> syntax

### ISSUE THREAD

**Issue by dmitriiabramov** [fkling/astexplorer#189]
related to https://github.com/facebook/jscodeshift/issues/172
is there a way to make astexplorer understand these type annotations?

example: https://astexplorer.net/#/QEsBbS2npj

**Comment by fkling** [comment]
Yep, there are two parts to it:

- Configure recast to use flow as parser. You can do that by clicking the cog icon next to recast and select "flow" from the "parser" option. This is only used for parsing the code and showing the AST. It's independent of jscodeshift.

- To enable the flow parser in for the transform, add `export const parser = 'flow';` to it: https://astexplorer.net/#/QEsBbS2npj/1 .

**Comment by dmitriiabramov** [comment]
@fkling that worked! thanks!
are there any plans for changing the defaults?
