### ISSUE TITLE
Error when loading jscodeshift

### ISSUE THREAD

**Issue by craigbilner** [fkling/astexplorer#192]
Hi, looks like the Webpack 2 upgrade has bust the modules when trying to do a transform, I can't build locally to debug or fix at work, but if you could rollback the website/fix it in the meantime that would be awesome, thanks.

**Comment by RReverser** [comment]
@craigbilner Transforms work great for me on the website, must be an issue with your browser or network connection.

**Comment by craigbilner** [comment]
@RReverser thanks for the speedy response. I've tried tethering to my phone instead and get the same error.

Choose recast
Choose jscodeshift from transform
```
ReferenceError: exports is not defined
...
Uncaught (in promise) ReferenceError: exports is not defined
```

**Comment by RReverser** [comment]
Details are important :) This seems to be something specific to jscodeshift, other transforms work for me.

**Comment by craigbilner** [comment]
@RReverser all transforms are bust for me? If I flick through them I get various chunking and script failures that look very Webpack 2 upgrade issuey?

**Comment by fkling** [comment]
I can confirm that there is an issue with loading jscodeshift. It seems like the culprit is disabling module transforms in babel, though I'm not sure why. I'll have a fix momentarily.

**Comment by fkling** [comment]
Eh, something else broke with the new version (works fine locally though), so I rolled the server back for now. I will investigate later when I have more time.

**Comment by craigbilner** [comment]
Thanks @fkling! Great tool btw

**Comment by fkling** [comment]
So, the reason why the new build didn't work (for me) was that the new build changed a file without changing the hash in the file name. Since JS files are cached for a long time, browsers wouldn't download the updated file.

I have to investigate why the filename wasn't updated...

**Comment by fkling** [comment]
It seems like the hashing happens before minification / optimization. I can only assume that the hash didn't change because the unminified content was the same. Not sure how removing module transpilation would only change the minified version though.

Anwyays, look like updating one of the vendor libraries might solve the issue (by enforcing a new hash).
