### ISSUE TITLE
Flow parser broken

### ISSUE THREAD

**Issue by pieterv** [fkling/astexplorer#194]
Looks like flow parser is giving errors for any input. I can see an error is getting thrown on input but can't figure out much from the minified stack. Could be related to the Flow 0.38 update? I swear it was working yesterday :/

<img width="780" alt="screen shot 2017-02-04 at 3 24 11 pm" src="https://cloud.githubusercontent.com/assets/438482/22622420/0e7e8388-eaee-11e6-884f-da8a5ff24df7.png">

http://astexplorer.net/#/gist/15d260aa669e8782baa75fadb6ef550e/2925a0598d3b75469f00721353eff48013d3df7b

cc @mroch @fkling

**Comment by fkling** [comment]
It seems to work when I run `yarn watch` locally. But it doesn't work when the bundle is minified. So it seems that babili is doing something to the bundle the breaks flow (cc @kangax).

I can try to play with the webpack configuration to exclude flow from being minified.

**Comment by fkling** [comment]
Should be fixed now.

**Comment by pieterv** [comment]
Awesome, its working! Thanks for the quick fix @fkling
