### ISSUE TITLE
Some parser are broken

### ISSUE THREAD

**Issue by lahmatiy** [fkling/astexplorer#195]
Currently some parsers aren't working on https://astexplorer.net/ due to exception:

![screen shot 2017-02-13 at 00 39 57](https://cloud.githubusercontent.com/assets/270491/22866297/14dd3d58-f185-11e6-9230-5b93a8ce0edd.png)

Broken parsers:

- postcss
- csstree 
- yaml-ast-parser
- handlebars

Other parsers work fine.

**Comment by fkling** [comment]
There still seems to be issues regarding caching and recalculating hashes. Hopefully this won't be a problem anymore with the changes I have planned (will post about it soon).
