### ISSUE TITLE
Uplift ESLint to v3

### ISSUE THREAD

**Issue by gyandeeps** [fkling/astexplorer#198]
Currently, the supported version of ESLint are v1 and v2. It been a long time since v3 has been out.

Proposal: Remove eslint v1 and add eslint v3.

If this proposal is fine then I can work on this.

**Comment by hzoo** [comment]
Sounds good, although fyi @fkling is working on https://github.com/fkling/astexplorer/pull/197 as well

**Comment by fkling** [comment]
@hzoo: Not sure how long that is going to take though.

I wouldn't necessarily remove eslint v1 ( #197 will allow you to pick the version anyway), but adding eslint v3 definitely makes sense. Have a look at how we create packages for v1 and v2. I don't know what changed between v2 and v3, hopefully there are not too many changes needed.
