### ISSUE TITLE
jscodeshift.registerMethods should be idempotent

### ISSUE THREAD

**Issue by aaronjensen** [fkling/astexplorer#22]
If I include a jscodeshift.registerMethods in my transform, it works the first time, but if I change the transform, I get an error: 

```
A method with name "findReturnsInCurrentScope" already exists.
```

I'd expect a fresh jscodeshift w/ no methods registered each iteration.

Repro:  http://felix-kling.de/esprima_ast_explorer/#/NvHouJt2GJ

Just open it, and make a change to the transform.

**Comment by fkling** [comment]
Thanks for pointing that out! Not sure how to get a fresh copy since that's not how modules work, but maybe we can expose some API to clear the registered methods.

**Comment by aaronjensen** [comment]
yeah, if it's not running in an iframe  it's tough. If the result runs in an iframe then you could just load it anew every time.

Otherwise, either a clear api or a "i know i'm overwriting methods" option to `registerMethods` would work.

**Comment by aaronjensen** [comment]
Thanks @RReverser and @fkling
