### ISSUE TITLE
Wrong version of css-tree

### ISSUE THREAD

**Issue by smelukov** [fkling/astexplorer#235]
Hi! `css-tree` version is wrong. It must be `alpha-17` (from [package.json](https://github.com/fkling/astexplorer/blob/master/website/package.json#L62)), but `alpha-9` is using.

**Comment by smelukov** [comment]
Most likely I found the reason of the problem https://github.com/yarnpkg/yarn/issues/3560

**Comment by fkling** [comment]
Sorry, I completely missed this issue. Thanks for the fix!
