### ISSUE TITLE
Improve UI for deeply nested ASTs

### ISSUE THREAD

**Issue by RReverser** [fkling/astexplorer#240]
![321d6c63-0725-4a84-b17c-9c0dc86e6383](https://user-images.githubusercontent.com/557590/27157006-828e36a4-5157-11e7-94b3-b0996198b5e2.png)

I've used jQuery source for demonstrating the issue, but there might be examples where AST gets blown up even by smaller files. This is especially unpredictable for non-JavaScript parsers which might have suboptimal AST layouts.

Ideally, we should find a way to automatically "zoom in" into separate nodes when going too deeply in the tree and provide a way to zoom back.

But as a first step, I think it would make sense to remove `overflow-y` on individual blocks in favor of a horizontal scrollbar on the entire area - I've tried to, but got some issues with highlighting.

**Comment by kindy** [comment]
I'm trying to fix the tree viewer in PR #285 too. even it's not perfect, but it's better than now.
maybe you'd like to have a look on it. :)

**Comment by j-f1** [comment]
Repro:

```js
function test() {
  if (foo) {
    bar = baz || function (quux) {
      if (quux) {
        quux()
      }
    }
  }
}
```

It would also be nice to decrease the indentation of each node’s properties — maybe two spaces instead of 3 1/2. This would make the current UI look good for slightly more deeply-nested trees.

**Comment by fkling** [comment]
I did this a while ago btw. Haven't decreased the indentation, but I'll look into that.
