### ISSUE TITLE
Support generic languages in transform

### ISSUE THREAD

**Issue by gabro** [fkling/astexplorer#248]
I'm playing around with a custom transformation in Scala (based on #247) and it seems like the source code of the transformation is required to be in JavaScript.

Is this the case, or I'm getting it wrong? If so, can this be generalized?

**Comment by RReverser** [comment]
Well the transforms are executed on the client-side (in the browser), so yeah, they have to be in JavaScript. Or do you want to put there some language that transpiles to JavaScript? That should work, too, but probably will require some tweaking around highlighting.

**Comment by gabro** [comment]
My idea would be to add scalafix, which can take source files defining transformations as an input.

Scalafix can be compiled to js, and be invoked in the browser. The only thing it would need is to access the content of the transform pane in its raw form.

**Comment by RReverser** [comment]
> The only thing it would need is to access the content of the transform pane in its raw form.

That's definitely possible, you don't have to run `transformJSCode` on the transform code, it's just for convenience for transformers that really use JS.

**Comment by fkling** [comment]
What @RReverser said. If you look at https://github.com/fkling/astexplorer/blob/93aa4be41e00e0754afc97c0f9eebd26d401eaca/website/src/parsers/js/transformers/jscodeshift/index.js#L47, `transformCode` is just a string. The transform can do with that whatever it wants.

**Comment by gabro** [comment]
I've tried to implement a test transform where I simply return the original code, but I still get syntax errors if transformCode is not valid JS code. I'm literally just doing 'return code', is there any setting I've missed?

**Comment by gabro** [comment]
At a first glance it seems like the TransformOutput component transforms the transformCode to ES5 before passing it to the transformer.
But I'm from the phone atm, so I might be getting it wrong

**Comment by fkling** [comment]
Oh you are right... maybe this is a good time to change how transformers work on the website. Instead of the site providing the `TransformOutput` component, I was thinking that every transformer should be able to specify what "view" to render.

E.g. something like the prettier transformer which uses the transform input as configuration source could provide a more specialized JSON editor. Or eslint could render two panels, one for errors and one for displaying the autofixed source.

Transformers who accept JavaScript as the transform could then use a special component that does the compilation.

**Comment by gabro** [comment]
That would make a lot of sense. A smaller step towards a less JS-only solution would be to also pass the raw input to the transformer. That's a small but very significant change, would you accept a PR for it?

**Comment by fkling** [comment]
>  A smaller step towards a less JS-only solution would be to also pass the raw input to the transformer.

Sure, that would work too. I guess that means moving the transform parsing to the transformers themselves.

**Comment by gabro** [comment]
In order to minimize the impact I was thinking of passing the rawInput as an *additional* parameter, would that make sense?

**Comment by fkling** [comment]
In that case I think an error  would still be thrown because the `TransformOutput` would still try to process the transform code?

**Comment by gabro** [comment]
Ops, yes, you're right. I guess moving the ES5 transformation to the transformers would be the way to go then.

**Comment by gabro** [comment]
@fkling here's a proposal https://github.com/fkling/astexplorer/pull/250

**Comment by fkling** [comment]
I ended up merging #290, if this is still of interest.

**Comment by olafurpg** [comment]
Thanks @fkling! It's good to know it's possible to write transforms in other languages. I would love to support Scala transforms on astexplorer but we would first need to get the Scala.js compiler running in JavaScript, which is not on the near roadmap.

I suppose this ticket can be closed @gabro ?

**Comment by gabro** [comment]
@olafurpg I guess it's still possible to allow writing syntactic transforms?

Anyway, I'll close this to clear up the issue queue.

**Comment by olafurpg** [comment]
We still need a compiler to compile the transformer code into JS even if the input file is syntactic.

**Comment by gabro** [comment]
Right, another approach is to send code over to a server (scastie style), but let's discuss this separately.
