### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by xtuc** [fkling/astexplorer#264]
This is a feature request for adding Golang as a parser.

Golang has a built-in support for parsing Go code ([go/ast](https://golang.org/pkg/go/ast/)) but it depends on #222 unless there is a parser implemented in JavaScript.

The built-in packages are a bit limited, there is no support for source maps.

**Comment by JAicewizard** [comment]
wasm anyone?

**Comment by RReverser** [comment]
@JAicewizard If you want to implement a PR, I'm sure it will be welcome.
