### ISSUE TITLE
Add Cherow to the list?

### ISSUE THREAD

**Issue by crazyhuggins** [fkling/astexplorer#277]
A new parser named [cherow](https://github.com/cherow/cherow) exist. Is it going to be supported?

**Comment by RReverser** [comment]
Sure, feel free to send PR! 😄

**Comment by crazyhuggins** [comment]
Hmm. Not sure I would know how to do that. Sorry! But will try to play around if I get time and see if I can understand this source, and create a PR.

**Comment by RReverser** [comment]
We tried to cover it in docs, should be as simple as copy-pasting one of existing parsers and adapting implementation to load & use cherow.

**Comment by RReverser** [comment]
Let me know if you run into any specific issues/questiona, will be happy to answer them.

**Comment by crazyhuggins** [comment]
I tried to implement this, but I ran into too much issues so I gave it up. And I don't have time to fight this either. Kind of issues? The list is too long.
