### ISSUE TITLE
A search bar that supports selectors

### ISSUE THREAD

**Issue by silvenon** [fkling/astexplorer#295]
AST Explorer has been an enormous help in writing ESLint rules and codemods. Another feature that I would die for is an instant way to test selectors right then and there.

For example, you would type `ImportDeclaration[source.value=react]` and it would highlight all import declarations from "react", i.e. matching that selector.

Is this something you would be interested in?

**Comment by j-f1** [comment]
👍 That would be cool.

**Comment by silvenon** [comment]
Never mind, I didn't know about the "Transform" feature! 🌟
