### ISSUE TITLE
"Hide location data" option doesn't persist after a syntax error.

### ISSUE THREAD

**Issue by blainehansen** [fkling/astexplorer#306]
When I check the "Hide location data" option, it only stays true while the input stays valid. If I type in something invalid (which very often happens while typing anything), the option is unchecked.

This is annoying since I'm just trying to understand the ast structure and not worrying about location data.

![peek 2018-03-20 14-18](https://user-images.githubusercontent.com/5805971/37680501-b8b3a75a-2c49-11e8-9230-2a747486639a.gif)

**Comment by fkling** [comment]
The reason for this was that the component would completely unmount and remount, causing the settings to be set to their default values. 

Since 488a092fbd33ce60c1863c3de8878732767f55b2, settings are now persisted in local storage, so this is not an issue anymore.
