### ISSUE TITLE
horizontal scrolling of AST nodes

### ISSUE THREAD

**Issue by jedwards1211** [fkling/astexplorer#332]
I don't know about other folks, but I think I would prefer being able to scroll the entire AST view horizontally instead of having scroll bars on the individual nodes.  As you can see here, it didn't work out too well with a deeply nested tree; the nodes get squinched:

![image](https://user-images.githubusercontent.com/1448194/43016945-24d6a920-8c1a-11e8-88ad-dc890fa01336.png)

**Comment by fkling** [comment]
It looks like this:

![screen shot 2018-09-09 at 9 50 35 pm](https://user-images.githubusercontent.com/179026/45351361-d2a52800-b56a-11e8-87bc-997cd8d94490.png)
