### ISSUE TITLE
Crashes when editing an example with a syntax error

### ISSUE THREAD

**Issue by jasonLaster** [fkling/astexplorer#336]
STR:
1. write this example
2. click somewhere in the editor

```js
await foo();

async function f() {}
```

it only stopped crashing when i did `localStorage.clear()`

**Comment by fkling** [comment]
Can you confirm that this happens in Chrome? It seems to work fine in Firefox.

Does it happen with any parser?

**Comment by jasonLaster** [comment]
i'll test next week and report back.

**Comment by fkling** [comment]
Wrote a quick fix. In Firefox it happened only when loading code from local storage (and snippet?), but not sure why.
