### ISSUE TITLE
babel-plugin-macros broken: "The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean."

### ISSUE THREAD

**Issue by sw-yx** [fkling/astexplorer#345]
something broke recently... just fire up a fresh astexplorer and select the babel-plugin-macros transform:

https://astexplorer.net/#/gist/5487bdb859dd3fd3940134af938f7d4b/3c0ba3060bf92a07af103c7203e42aa29034dc01

which errors out of the box

![image](https://user-images.githubusercontent.com/6764957/46091177-47d64700-c180-11e8-8b01-22c7887e9dfa.png)

which is probably related to your recent commit, which i am not sure is deployed: https://github.com/fkling/astexplorer/commit/e931c0546b42fb3d7204756efa831d5c1488df56

**Comment by sw-yx** [comment]
@skevy's commit as well https://github.com/fkling/astexplorer/commit/9dab028a0b0c6684e4192e46765d91564a20ba11

**Comment by sw-yx** [comment]
ah. thanks felix. you are super freaking awesome, didnt expect a response so soon! closing for now

**Comment by fkling** [comment]
Published!
