### ISSUE TITLE
Current deployed version is broken

### ISSUE THREAD

**Issue by probablyup** [fkling/astexplorer#347]
If you click into the left editor pane the app crashes with a minified React error

**Comment by fkling** [comment]
Please provide the following information:

- Browser type and version
- Selected parser and/or transformer

**Comment by probablyup** [comment]
chrome 69

explorerSettingsV1:
```
{"showTransformPanel":false,"parserSettings":{},"parserPerCategory":{},"workbench":{"parser":"acorn-to-esprima","code":"import styled from \"styled-components\"\n\n\n","transform":{"code":"","transformer":null}}}
```

<img width="1439" alt="screen shot 2018-09-28 at 1 29 32 am" src="https://user-images.githubusercontent.com/570070/46191669-f92ec700-c2bd-11e8-9ff9-33b7c59ed6e1.png">

**Comment by fkling** [comment]
Yeah, there is some issue with `acorn-to-esprima`, that causes something to crash.

That's why I hid it from the menu.
