### ISSUE TITLE
ReasonML/OCaml support

### ISSUE THREAD

**Issue by farskid** [fkling/astexplorer#350]
This is a feature request.

Requesting support for ReasonML support which uses OCaml as a supporting background programming language which means support for OCaml can come out of the box as well.

[BuckleScript](https://github.com/BuckleScript/bucklescript) is the translation layer currently binding OCaml compiler to javascript. So AST can be handled the same way they're handling it probably. (**Just a suggestion**)

I'd be also happy to pick it up and work on it if someone can help me with it.

**Comment by fkling** [comment]
I'm happy to help with the integration into  astexplorer, I don't know anything about the OCaml -> JavaScript part.
