### ISSUE TITLE
Current `master` branch fails to build

### ISSUE THREAD

**Issue by asmironov** [fkling/astexplorer#355]
Current `master` branch fails to build.

**Steps to reproduce:**
1. Clone the repository.
2. Go to `/website`.
3. Run `yarn install`.
4. Run `yarn build`.

**Expected behavior:**
`astexplorer` builds successfully.

**Actual behavior:**
Multiple build errors, all similar to the following: 
```
ERROR in ./node_modules/acorn-loose/dist/acorn-loose.mjs 37:15-19
Can't import the named export 'Node' from non EcmaScript module (only default export is available)
 @ ./src/parsers/js/acorn.js
 @ ./src/parsers sync ^\.\/(?!utils|transpilers)[^\/]+\/(transformers\/([^\/]+)\/)?(codeExample\.txt|[^\/]+?\.js)$
 @ ./src/parsers/index.js
 @ ./src/storage/parse.js
 @ ./src/app.js
```

**System info:**
- Windows 10 Pro (1709)
- node v9.4.0
- yarn v1.12.3

I believe it's connected to `acorn-loose` or `webpack` versions. I'm not sure if it's related to hats and tildes in `package.json`, but I've tried to remove all of them and then `yarn install` and `yarn build` once again with same result.

**Comment by fkling** [comment]
Closing since this has never been an issue for me. Feel free to reopen if this occurs again.
