### ISSUE TITLE
Add support for Solidity parser

### ISSUE THREAD

**Issue by thith** [fkling/astexplorer#374]
Solidity is the language used to write smart contracts for Ethereum blockchain. There's a parser here https://github.com/federicobond/solidity-parser-antlr

**Comment by fkling** [comment]
Interesting. There are parsers for everything 😆 

Feel free to open a PR.

**Comment by thith** [comment]
> Interesting. There are parsers for everything 😆
> 
> Feel free to open a PR.

I added #382
