### ISSUE TITLE
Configuring parser options for @typescript-eslint/parser

### ISSUE THREAD

**Issue by vivekgalatage** [fkling/astexplorer#379]
**Specify additional parser options for the @typescript-eslint/parser**
 
For using certain features like import statements, the @typescript-eslint/parser requires the options to be configured properly such as { sourceType: "module", ecmaVersion: 6 }

Currently only these options are supported:

![https://user-images.githubusercontent.com/1282684/51980306-afe1c480-24b5-11e9-85b7-8b380077b710.png](https://user-images.githubusercontent.com/1282684/51980306-afe1c480-24b5-11e9-85b7-8b380077b710.png)

Example can be found [1] which results in ImportDeclaration should appear when the mode is ES6 and in the module context. this message being shown instead of the AST!

[1] https://astexplorer.net/#/gist/7e50441d4cc006738fd2ff60fa07bed0/7ac7aa8b43549643d618d583ee838e75dfe8eb97

What is the way in which these options can be passed on https://astexplorer.net/

**Comment by fkling** [comment]
Only the options shown there can be set. To enable more options they need to be added to https://github.com/fkling/astexplorer/blob/8b30e3d79498804bedfda4d4c802538fe0c60f5e/website/src/parsers/js/typescript-eslint-parser.js#L23-L55

cc @ikatyang
