### ISSUE TITLE
babel macro transform is broken (TypeError: i.statSync is not a function)

### ISSUE THREAD

**Issue by sw-yx** [fkling/astexplorer#380]
**Describe the bug**

normal usage doesnt work

**To Reproduce**
https://astexplorer.net/#/gist/a1fe701789ebb445dd743f175a3df1c2/3a28850d473c48f9dbbdeec0da186c58eae40f94

**Expected behavior**
it should work

**Screenshots**
![image](https://user-images.githubusercontent.com/6764957/52342367-4e3fbf80-29b9-11e9-9002-6055114beb5b.png)

**Browser (please complete the following information):**
 - OS: [e.g. iOS] os x
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] current

**astexplorer settings:**
- Selected parser: [e.g. acorn] babylon7
- Selected transformer (if applicable): [e.g. jscodeshift] babel plugin macros
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)

```
{"showTransformPanel":true,"parserSettings":{},"parserPerCategory":{},"workbench":{"parser":"babylon7","code":"import gemmafy from 'gemmafy.macro'\nconsole.log(gemmafy('hello world'))","keyMap":"default","transform":{"code":"module.exports = createMacro(gemmafyMacro)\nfunction gemmafyMacro({ references, state, babel }) {\n  references.default.forEach(referencePath => {\n    const [firstArgumentPath] = referencePath.parentPath.get('arguments')\n    const stringValue = firstArgumentPath.node.value\n    const gemmafied = stringValue.split(' ').join(' 🐶 ')\n    const gemmafyFunctionCallPath = firstArgumentPath.parentPath\n    const gemmafiedStringLiteralNode = babel.types.stringLiteral(gemmafied)\n    gemmafyFunctionCallPath.replaceWith(gemmafiedStringLiteralNode)\n  })\n}","transformer":"babel-plugin-macros"}}}
```

**Comment by fkling** [comment]
I can reproduce this. Looks like the transformer tries to load the file `gemmafy.macro` is supposed to resolve to. Not sure what changed between when it was originally added and now.

cc @kentcdodds

**Comment by sw-yx** [comment]
couple of forensic notes

- it has to have happened in the last 2-3 months, as i didnt have issues back in nov/dec
- happens on all `*.macro` stuff, not just `gemmafy.macro`

**Comment by pshrmn** [comment]
This issue is caused by `babel-plugin-macros`. https://github.com/kentcdodds/babel-plugin-macros/issues/102
