### ISSUE TITLE
[NEED HELP] Creating a jscodeshift transform for glimmer

### ISSUE THREAD

**Issue by rajasegar** [fkling/astexplorer#387]
I have created a codemod within [astexplorer](https://astexplorer.net/#/gist/b128d5545d7ccc52400b922f3b5010b4/571266d8c29cb8eb1bd5730c0c388526081cce46) for transforming Handlebars curly brace syntax to Angle brackets syntax proposed by this RFC https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md
But i am unable to find any documentation or ref on how to convert this to a proper transform that can be executed by jscodeshift. 
Here is the codemod repo 
https://github.com/rajasegar/ember-angle-brackets-codemod
It is throwing a syntax error like this:
` ERR source.handlebars Transformation error (Cannot match against 'undefined' or 'null'.)
TypeError: Cannot match against 'undefined' or 'null'.
    at syntax (/Users/user/Documents/www/emberjs/ember-angle-brackets-codemod/transform.js:24:56)
All done. 
`

**Comment by rajasegar** [comment]
This is how I ended up with so far. Please let me know if this is correct.

```js
const glimmer = require('@glimmer/syntax');
module.exports = function(fileInfo, api, options) {
  const ast = glimmer.preprocess(fileInfo.source);

  glimmer.traverse(ast, {
      MustacheStatement(node) {
        // Put your transform logic here
      },
      BlockStatement(node) {
        // Put your transform logic here
      }
  });
  return glimmer.print(ast);
};
```

Reference: https://github.com/rajasegar/ember-angle-brackets-codemod/blob/master/transforms/angle-brackets/transforms/angle-brackets-syntax.js

**Comment by fkling** [comment]
Sorry for not responding earlier, but yes, that looks right to me.

jscodeshift really consists of two parts: 

- A "runner" that processes that passes each selected file to the transform script
- A "transform library" that can parse, mutate and print JavaScript code

The library is passed to the transform scripts, but you don't have to use it if you are not actually dealing with JavaScript files. The transform file can process the file content however it wants.

**Comment by rajasegar** [comment]
Thanks @fkling
