### ISSUE TITLE
Flow typecast works with AST but causes error in jscodeshift

### ISSUE THREAD

**Issue by Daniel15** [fkling/astexplorer#393]
**Describe the bug**
When using a the Flow parser along with some code that has a Flow typecast on a string, the AST appears correctly, but a jscodeshift transform throws a syntax error.

**To Reproduce**
Basic example: https://astexplorer.net/#/gist/436869037a72a72742030d1c66cd16fc/765d1e39c58b9cf843b218994516ffe1a4e892fa
Input:
```
AdsAccountUtils.hasCapability(('VIEW_TAGS': AdsAccountCapabilitiesType))
```

Transform:
```
export default function transformer(file, api) {
  const j = api.jscodeshift;
  return j(file.source).toSource();
}
```

**Expected behavior**
No syntax error

**Browser (please complete the following information):**
 - OS: Windows 10, version 1809
 - Browser: Firefox 66.0.2

**astexplorer settings:**
- Selected parser: Flow
- Selected transformer: jscodeshift
- Contents of the local storage key `explorerSettingsV1`:
```
{"showTransformPanel":true,"parserSettings":{},"parserPerCategory":{"javascript":"flow"},"workbench":{"parser":"flow","code":"AdsAccountUtils.hasCapability(('VIEW_TAGS': AdsAccountCapabilitiesType))","keyMap":"default","transform":{"code":"export default function transformer(file, api) {\n  const j = api.jscodeshift;\n  return j(file.source).toSource();\n}\n","transformer":"jscodeshift"}}}
```

**Comment by j-f1** [comment]
This is because you can’t currently change the parser used by the transformer. Changing the parser just changes the AST tree view.

**Comment by fkling** [comment]
@j-f1 is right in so far that changing the parser in the settings only changes the view, but not the transformer. But jscodeshift lets you specify the parser from the transform, [as explained in the readme](https://github.com/facebook/jscodeshift#parser).

So to choose flow, you have to add

```js
export const parser = 'flow';
```
