### ISSUE TITLE
Filter checkboxes produce React warnings

### ISSUE THREAD

**Issue by RReverser** [fkling/astexplorer#395]
Currently when clicking on either of the filter checkboxes ("Hide methods", "Hide empty keys", etc.) with devtools open against a dev instance of ASTExplorer, you can see following React warnings:

> Warning: A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.

I'm not a React expert, but these should probably be addressed.

**Comment by fkling** [comment]
Should be resolved now with 488a092fbd33ce60c1863c3de8878732767f55b2 .

**Comment by RReverser** [comment]
Thanks!
