### ISSUE TITLE
Switching the Handlebars parser causes an error

### ISSUE THREAD

**Issue by Turbo87** [fkling/astexplorer#398]
**Describe the bug**

When selecting the "Handlebars" language and switching the parser the whole page turns white and the console is showing an error:

```
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.getOffset (defaultHandlebarsParserInterface.js?2a65:18)
    at eval (defaultHandlebarsParserInterface.js?2a65:23)
    at Array.map (<anonymous>)
    at Object.nodeToRange (defaultHandlebarsParserInterface.js?2a65:23)
    at Element.render (Element.js?d8fd:214)
    at finishClassComponent (react-dom.development.js?61bb:14695)
    at updateClassComponent (react-dom.development.js?61bb:14650)
    at beginWork (react-dom.development.js?61bb:15598)
    at performUnitOfWork (react-dom.development.js?61bb:19266)
    at workLoop (react-dom.development.js?61bb:19306)
```

(the above stacktrace was taken locally to generate better path information)

**To Reproduce**

1. Select the "Handlebars" language
2. Select a different parser than the currently selected one
3. See error

**Expected behavior**

I expect the parser to change and the AST to update

**Browser (please complete the following information):**
 - OS: OS X
 - Browser: Chrome and Firefox

**astexplorer settings:**
- Selected parser: [e.g. acorn]
- Selected transformer (if applicable): [e.g. jscodeshift]
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)
```
{"showTransformPanel":false,"parserSettings":{"esprima":{"sourceType":"module","loc":false,"range":true,"tokens":false,"comment":false,"attachComment":false,"tolerant":true,"jsx":true},"espree":{},"recast":{"tolerant":false,"range":true,"parser":"babylon6","flow":{"esproposal_class_instance_fields":true,"esproposal_class_static_fields":true,"esproposal_decorators":true,"esproposal_export_star_as":true,"types":true},"babylon":{"sourceType":"module","allowImportExportEverywhere":false,"allowReturnOutsideFunction":false,"plugins":["asyncGenerators","classConstructorCall","classProperties","decorators","doExpressions","exportExtensions","functionSent","functionBind","jsx","objectRestSpread","dynamicImport"]}}},"parserPerCategory":{"handlebars":"ember-template-recast","javascript":"recast","htmlmixed":"htmlparser2"},"workbench":{"parser":"ember-template-recast","code":"<div class=\"entry\">\n  <h1>{{title}}</h1>\n  <div class=\"body\">\n    {{\"j\"}}\n  </div>\n</div>\n","transform":{"code":"// Press ctrl+space for code completion\nexport default function transformer(file, api) {\n  const j = api.jscodeshift;\n\n  return j(file.source)\n    .find(j.Identifier)\n    .forEach(path => {\n      j(path).replaceWith(\n        j.identifier(path.node.name.split('').reverse().join(''))\n      );\n    })\n    .toSource();\n}\n","transformer":"jscodeshift"}}}
```

**Additional context**

I have git bisected the issue locally, which resulted in 1d561f6 being the first bad commit:

```
1d561f69c583b77d995b9a98a00acc7c9a0539d8 is the first bad commit
commit 1d561f69c583b77d995b9a98a00acc7c9a0539d8
Author: Felix Kling <felix.kling@gmx.net>
Date:   Wed Apr 24 00:47:23 2019 -0700

    Add parser/parsing middleware

    This moves the actual parsing process from the ASTOutput component into
    a redux middleware. Decoupling the parsing process from UI components is
    the first step in refactoring how parsers return results, and more
    generally how UI components interact with parsers and parse results.
```

/cc @fkling

**Comment by fkling** [comment]
Thank you for reporting and sorry for that. No idea what the issue could be, I'll try to take a look today.

**Comment by Turbo87** [comment]
it looks like `nodeToRange()` is called before `parse()`, which doesn't work because at that point the line offsets array hasn't been filled yet. it seems that the new Rust parser is using similar code, but since there is only one parser for it so far, it does not seem to have the same issue.

**Comment by fkling** [comment]
Yes, I just came to the same conclusion. I'm actually working on refactoring how all of that works and the changes I've made so far seem to resolve that issue so I will just commit those after some more testing.

**Comment by fkling** [comment]
Try `https://latest.astexplorer.net`. It seems to work fine for me. If everything else works fine, I'll merge it into stable tonight.

**Comment by fkling** [comment]
Since everything seems to work, the fix is now also available on https://astexplorer.com . Please let me know if you encounter any other issues.

**Comment by Turbo87** [comment]
yep, seems to work. thanks for the quick response! :)
