### ISSUE TITLE
Support private fields & methods

### ISSUE THREAD

**Issue by jhpratt** [fkling/astexplorer#402]
[Private fields](https://github.com/tc39/proposal-class-fields#private-fields) and [private methods](https://github.com/tc39/proposal-private-methods#private-methods-and-fields) are both stage 3 proposals, and private fields have already shipped in Chrome.

Having support for parsing these would be great! It looks like it's [this file](https://github.com/fkling/astexplorer/blob/master/website/src/parsers/js/babylon7.js) that needs to be updated — I'm not entirely sure what the issue is with it, since it already lists both syntaxes.

**Comment by RReverser** [comment]
ASTExplorer supports lots of programming languages and parsers. It would be helpful to specify which ones you have in mind when filing an issue, or better yet, just submit a PR that updates a corresponding parser.

**Comment by jhpratt** [comment]
Babel, sorry!

**Comment by fkling** [comment]
These options are already available, in https://github.com/fkling/astexplorer/blob/3125e5b29039db604cc61373fd178121f1f6211f/website/src/parsers/js/babylon7.js#L19-L21

You just need to enable them:

![Screen Shot 2019-05-06 at 11 52 01 PM](https://user-images.githubusercontent.com/179026/57278030-4f38c980-705a-11e9-9468-4e6ebcb58774.png)

Making settings more discoverable is on my todo list.

**Comment by jhpratt** [comment]
Ah, I'd just assumed the cog was part of the hover for selecting the syntax, not to _configure_ the syntax. That certainly explains why, when I looked at the code, I didn't see anything wrong with it!

Thanks, hope this serves as a marker for others.
