### ISSUE TITLE
Update Babel 7 to latest

### ISSUE THREAD

**Issue by jhpratt** [fkling/astexplorer#412]
Simple request here: could the version of Babel be updated to the latest (currently 7.4.5)? It's currently on 7.3.4. "syntactic placeholders" are new in 7.4 [[docs](https://babeljs.io/docs/en/babel-template)], and it would be great to be able to use these in plugins — it allows some things not previously allowed.

**Comment by fkling** [comment]
Babel has been updated in the meantime, thank you!
