### ISSUE TITLE
Throwing maximum call stack size when using graphql ast explorer

### ISSUE THREAD

**Issue by sibelius** [fkling/astexplorer#418]
**Describe the bug**
RangeError: Maximum call stack size exceeded
    at Generator.invoke [as _invoke] (vendors~app-b405fe47e1d812255743-26.js:38)
    at Generator.e.<computed> [as next] (vendors~app-b405fe47e1d812255743-26.js:38)
    at getFocusPath 

**To Reproduce**
Go to https://astexplorer.net/, and add a big schema.graphql content

**Expected behavior**
It should not throw error

**Screenshots**
![image](https://user-images.githubusercontent.com/2005841/61225062-343ba300-a6f6-11e9-8788-4d97b4984035.png)

**Browser (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Chrome

**astexplorer settings:**
- Selected parser: [e.g. acorn] graphql
- Selected transformer (if applicable): [e.g. jscodeshift]
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)

**Additional context**

**Comment by fkling** [comment]
Is there any way you can share the schema? I guess the good news is that #401 actually removes `getFocusPath` so this may not be an issue anymore in the future. But it would be helpful to be able to reproduce the the issue.

**Comment by sibelius** [comment]
it is not happening anymore

it was hard to figure it out what part of the schema was causing the trouble, I think it was when I copy and pasted a very large graphql schema

tks
