### ISSUE TITLE
Possible to use async / Promises with astexplorer in adding parser?

### ISSUE THREAD

**Issue by kaymccormick** [fkling/astexplorer#432]
I'm writing a parser and I integrated it into astexplorer, but I have change it to return promise instead of directly returning value. This is for specific reasons unrelated to ast explorer,but is it possible to integrate this without much effort? I will dig into the code to try and make this happen.

**Comment by fkling** [comment]
Yes, promises returned from the `parse` method are already supported. This is the code that calls into the selected parser:

https://github.com/fkling/astexplorer/blob/94bd223c854614945c8c71cb66dbf170e505eab8/website/src/store/parserMiddleware.js#L4-L15
