### ISSUE TITLE
Site doesn't load

### ISSUE THREAD

**Issue by jridgewell** [fkling/astexplorer#456]
The website appears to be broken.
<img width="1231" alt="Screen Shot 2019-11-08 at 9 37 10 PM" src="https://user-images.githubusercontent.com/112982/68521527-f39d0200-026f-11ea-8a45-c6b0062f2e4b.png">

**Comment by fkling** [comment]
I'm rolling back to a previous deployment.
Not sure what's wrong, https://staging.astexplorer.net works fine in the meantime.

**Comment by fkling** [comment]
Mmh, that didn't work either. I temporarily linked astexplorer..net to stagining.astexplorer.net so that it can at least serve a development build.

**Comment by fkling** [comment]
Never mind, I'm a clown and I successfully rolled back now.

Still not sure what's broken with the build process though. Development builds work fine, but production builds seems to be missing the vendors JS file...

**Comment by fkling** [comment]
It looks the issue was caused by setting `splitChunks.name` to `false`. The corresponding assets were not emitted. It seems to work now.

**Comment by jridgewell** [comment]
Thanks for the updates!
