### ISSUE TITLE
If I chosen eslint as transformer, how can I get the return error?

### ISSUE THREAD

**Issue by YuunYang** [fkling/astexplorer#471]
Like this example, I want it mention `xx is not defined`, like this 👇
![image](https://user-images.githubusercontent.com/15278220/70412470-d7b79680-1a8f-11ea-9056-b9659ec9dacc.png)
But I can't find it 
![image](https://user-images.githubusercontent.com/15278220/70412570-0f264300-1a90-11ea-9208-2b31eacb88bb.png)

Is there any other tricks? my English is not good, maybe I ignored some point?

**Comment by fkling** [comment]
Sorry for the late reply. I'm not *quite* sure what you want to know.

If you want to get the same report in astexplorer as you get in your IDE, then that's not possible. As you can see from the popup, the error is thrown by the `react` esling plugin. astexplorer doesn't allow you do load existing plugins. It lets you create your own plugin.

If you are asking how to write a plugin that would throw as similar error, I would suggest to look at the implementation of the `react` plugin or other plugins.

**Comment by YuunYang** [comment]
Sorry for not reply in time, I find it was not astexplorer's problem, and I solved this issue by using eslint, sorry for disturb
