### ISSUE TITLE
jscodeshift transform with `functionTypeAnnotation` is producing invalid syntax

### ISSUE THREAD

**Issue by bcutler-work** [fkling/astexplorer#472]
**Describe the bug**
Trying to insert a `functionTypeAnnotation` is producing an extra colon `:`

**To Reproduce**

Example gist: https://astexplorer.net/#/gist/13c0f5e71abc84f6bcd3d87962d37824/ed5f6c0f9870692f21a50ebc9f7017e90bbe672a

**Expected behavior**

The produced interface should look like:

`interface Test { func: () => void }`

not

`interface Test { func: : () => void }`

**Browser (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 79

**astexplorer settings:**
- Selected parser: babylon7
- Selected transformer (if applicable): jscodeshift
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)
```
{"showTransformPanel":true,"parserSettings":{},"parserPerCategory":{"javascript":"babylon7"},"workbench":{"parser":"babylon7","code":"// no real code","keyMap":"default","transform":{"code":"// Press ctrl+space for code completion\nexport default function transformer(file, api) {\n  const j = api.jscodeshift;\n\n  return j(file.source)\n    .find(j.Program)\n    .forEach(path => {\n      path.value.body.unshift(j.interfaceDeclaration(j.identifier(\"Test\"), j.objectTypeAnnotation([j.objectTypeProperty(j.identifier(\"func\"), j.functionTypeAnnotation([], j.voidTypeAnnotation(), null, null), false)]), []));\n    })\n    .toSource();\n}\n","transformer":"jscodeshift"}}}
```

**Additional context**

I assume this is not actually a bug with the site itself, but I'm honestly not sure which package is responsible for the step that seems to be broken. Could be jscodeshift, or maybe recast?

If the input to the transform itself is invalid (is it expecting a value there, but there's nothing, so it just outputs a blank string with a colon attached?) I would expect an error of some sort, not code that fails to syntax check.

**Comment by fkling** [comment]
Yeah, this is very unlikely to be an issue with astexplorer itself. This could be an issue with recast since it is responsible for printing the AST. I would suggest to try to use recast directly and see if you can reproduce the error (if this is still a problem for you, I know the issue is relatively old).
