### ISSUE TITLE
uglify-js: "TypeError: Cannot read property 'endpos' of undefined"

### ISSUE THREAD

**Issue by edbrannin** [fkling/astexplorer#476]
**Describe the bug**
When pasting certain code into AST Explorer and trying to expand the tree, the app crashes and suggests I submit a bug report.

```
TypeError: Cannot read property 'endpos' of undefined
    at Object.nodeToRange (parsers~app-3a4f0ca4f9b7d297d9f8-27.js:1)
    at TreeAdapter.getRange (app-ffffa9c2e8d75dbf447b-27.js:1)
    at Element (app-ffffa9c2e8d75dbf447b-27.js:1)
    at [minified...]
```

**To Reproduce**
1. Go to https://astexplorer.net/
2. Turn off Transform
3. Set Parser to uglify-js
4. Paste the below code into the left panel
5. Click on the lower `Const`, then `VarDef` (see screenshot)
6. Look at the JS console for the error

```
const libVar = require('./anotherFile')

function aFunction() {
  // this is not working
  async.series([ _.curry(libVar.referencedFn) ])
  libVar.aFnInAnotherFile(n + 1)
}
libVar.aFnInAnotherFile(2)
aFunction()
// this is not working
var b = libVar.referencedFn


const anArrowFunc = (a, b) => {
  libVar.anArrowFuncInAnotherFile(
    a + b
  )
}
anArrowFunc(2, 3)
```

**Expected behavior**
Expand the `VarDef`; not crash the app

**Screenshots**

![image](https://user-images.githubusercontent.com/121909/72109227-74758a00-3303-11ea-8ded-10e7a1f907e0.png)

**Browser (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 79

**astexplorer settings:**
- Selected parser: `uglify-js`
- Selected transformer (if applicable): N/A
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)

```
{
  "showTransformPanel": false,
  "parserSettings": {},
  "parserPerCategory": {
    "javascript": "uglify-js"
  },
  "workbench": {
    "parser": "uglify-js",
    "code": "const libVar = require('./anotherFile')\n\nfunction aFunction() {\n  // this is not working\n  async.series([ _.curry(libVar.referencedFn) ])\n  libVar.aFnInAnotherFile(n + 1)\n}\nlibVar.aFnInAnotherFile(2)\naFunction()\n// this is not working\nvar b = libVar.referencedFn\n\n\nconst anArrowFunc = (a, b) => {\n  libVar.anArrowFuncInAnotherFile(\n    a + b\n  )\n}\nanArrowFunc(2, 3)\n",
    "keyMap": "default",
    "transform": {
      "code": "// redacted, irrelivent",
      "transformer": "eslint-v4"
    }
  }
}

```

**Additional context**
(n/a)

**Comment by fkling** [comment]
It looks like that the arrow function in that position doesn't have a value for `end`. This could be a bug in the parser because arrow functions in other places have a value set.

Regardless it's easy to code defensively to handle this case.
