### ISSUE TITLE
Whitespace in values is collapsed

### ISSUE THREAD

**Issue by Turbo87** [fkling/astexplorer#478]
**Describe the bug**

When using the Handlebars parser and looking at the value of a `TextNode` (`chars` attribute), I would expect the value to display whitespace characters correctly, but due to the default whitespace collapsing of the browser they are only shown as a single space character instead, which can be quite confusing.

**To Reproduce**
1. Go to https://astexplorer.net/#/gist/179c0fc002d69cbac732c71e00e7a5bc/1d3aed24698ba0cf5f3fedd6025e61ee7f29eeb4
2. Click on 'bar'
3. See `" bar\n"` in `chars` of the selected `TextNode`

**Expected behavior**
like in JSON mode, I would expect to see `"      bar\n"` instead. (thanks GitHub for collapsing the whitespace too 😅)

```
"      bar\n"
```

**Browser (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox, Safari, ...

**astexplorer settings:**
- Selected parser: Handlebars

**Additional context**

I would suggest to put `white-space: pre-wrap;` on the `.value` CSS class to resolve this issue.

**Comment by jedwards1211** [comment]
Same goes for `JSXText` nodes
