### ISSUE TITLE
[feature] Python typed-ast

### ISSUE THREAD

**Issue by graingert** [fkling/astexplorer#482]
add https://pypi.org/project/typed-ast/ to the explorer

**Comment by fkling** [comment]
I assume there isn't a JS version of this available? Unfortunately astexplorer doesn't support server side parsers yet.

**Comment by Glavin001** [comment]
Could we use https://www.npmjs.com/package/filbert ?

**Comment by Glavin001** [comment]
I've created a Pull Request using Filbert for Python: https://github.com/fkling/astexplorer/pull/521
