### ISSUE TITLE
Site hangs with recast+typescript+comment

### ISSUE THREAD

**Issue by evmar** [fkling/astexplorer#494]
**Describe the bug**
If you pick the recast+typescript parser then type '//' the site hangs.  The only way to recover is to kill the tab, then go into your browser settings and clear site data, because even if you reload the site it restores the settings across loads and causes it to hang on startup.

**To Reproduce**
1. Pick the recast parser.
2. Click the gear, pick 'typescript'.
3. Type `//`
4. See site hang

**Browser (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 82.0.4082.0 (Official Build) dev (64-bit)

**astexplorer settings:**
Described above.

**Comment by fkling** [comment]
The same happens when you click inside the comment in the default example.

The problem is that we are feeding location nodes into the autofocus logic, and that the location nodes in recast contain recursive information. I need to find a not horrible way to ignore location nodes in this situation.

**Comment by fkling** [comment]
Seems to work. Not sure whether it's because of recast changes or because I fixed it at some point.
