### ISSUE TITLE
postcss does not work anymore since last build

### ISSUE THREAD

**Issue by erganmedia** [fkling/astexplorer#496]
parsing with postcss does not work anymore. if you select postcss then it only shows "t is not a function"..
yesterday it worked well..

just test it https://astexplorer.net/

**Comment by fkling** [comment]
Can you share your parser settings/a screenshot? I can load the parser just fine but maybe it's a caching thing.

**Comment by erganmedia** [comment]
you are right.. in an incognito tab it works..
but here the screenshot anyways

![image](https://user-images.githubusercontent.com/18619741/79467827-83549280-7ffe-11ea-8b98-611f18d3bd30.png)

**Comment by fkling** [comment]
Does Shift+reload help? Or removing the astexplorer settings from local storage?

**Comment by fkling** [comment]
I'm closing this since I guess it was a caching issue.

**Comment by erganmedia** [comment]
btw it was not a cache problem.. there was an entry in my localstorage. I removed it and it worked

**Comment by fkling** [comment]
Thanks for letting me know!
