### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by SukantPal** [fkling/astexplorer#498]
The site doesn't work on Safari (macOS Catalina). It shows a blank site (with header & footer only).

<img width="1436" alt="Screen Shot 2020-04-22 at 5 14 04 PM" src="https://user-images.githubusercontent.com/22450567/80034597-ac709980-84bc-11ea-9e74-587694f57089.png">

**Comment by fkling** [comment]
Uh, that is unfortunate. I just pushed a change that restructures some of the elements and makes more use of flexbox. That might be the issue.
Did the site work for you before? Are there any other errors in the console?

**Comment by SukantPal** [comment]
@fkling I used the site for the first time today. The console is blank when I open it.
<img width="1436" alt="Screen Shot 2020-04-22 at 6 27 45 PM" src="https://user-images.githubusercontent.com/22450567/80039937-f8284080-84c6-11ea-9f5f-9001fe6677de.png">

**Comment by fkling** [comment]
OK. I will look into that. I only asked to get an idea whether the issue 
is the last layout change or not.

**Comment by SukantPal** [comment]
@fkling No problem, and thank you for this fantastic website. It works on Brave browser for me, for now. It has greatly helped me understand Babel's AST.

**Comment by raweden** [comment]
I also experienced this issue. Unsure about the exact timing, but it worked perfect about just over a month ago. The two issues I found in safari where; the Toolbar hover menus being cut off by the `overflow:hidden` css property on the `#Toolbar` element and the main editor split view being displaced somewhere so it won't be displayed at all, this displacement is due to the `position:relative` is working as intended on this element due to the flex based layout.

Chrome does not have the same or any problem displaying this correctly.

Note aside; it doesn't work in the latest Safari Technology Preview either.

**Comment by earksiinni** [comment]
For people coming from a web search (and echoing @rawden's comment), here's the workaround (disable the `position: relative` rule on `div.splitpane-content`):

<img width="1440" alt="Screen Shot 2020-04-28 at 5 37 29 PM" src="https://user-images.githubusercontent.com/5427394/80551111-39ad6580-8977-11ea-9b34-542bfc47762f.png">

**Comment by fkling** [comment]
Thank you all for the debugging help, that's really helpful :slightly_smiling_face: 

> Looks like there are a lot of nested position: absolute rules in the hierarchy of div.splitpane-content's descendants that's complicating rendering on Safari.

Yeah, I wanted to migrate all that to flex box but couldn't get it to work like I wanted it to.

I will try to fix this today or tomorrow.

**Comment by devongovett** [comment]
I get `TypeError: undefined is not an object (evaluating 'o.plugins.map')`

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/19409/80928546-270da480-8d5a-11ea-83ee-75e960225c98.png">

**Comment by earksiinni** [comment]
Just wondering whether there's been any progress on this.

**Comment by fkling** [comment]
@devongovett: Might be worth filing a separate issue about this, including parser settings.

@earksiinni: I started rewriting the whole splitpane implementation using flexbox instead and made some good progress but I'm not quite done yet. Sorry.

**Comment by fkling** [comment]
I have a commit that should fix the issue: https://github.com/fkling/astexplorer/commit/541552fe45885c225fbb67d54dc4c6d6107b65b5

It seems to work fine in my tests, but I would appreciate it if you could give it a try as well. I will comment here again when that commit is pushed to https://staging.astexplorer.net for testing.

Thank you!

**Comment by fkling** [comment]
The commit is now available on https://staging.astexplorer.net/ . Please give it a try and let me know how it goes.

**Comment by fkling** [comment]
The commit is now available on https://staging.astexplorer.net (you might have to do a force refresh). Please let me know how it goes!

**Comment by fkling** [comment]
And I already found an issue but nothing major :laughing:  (horizontal scrollbar position in ast output).

**Comment by fkling** [comment]
I published the changes. If you encounter any issues feel free to reopen the issue.

**Comment by earksiinni** [comment]
Works great so far! Thanks @fkling
