### ISSUE TITLE
Babylon should be renamed as @babel/parser

### ISSUE THREAD

**Issue by AjayPoshak** [fkling/astexplorer#502]
**Describe the bug**

Babylon is the old name for babel parser. It is no more used in documentation also. So it is confusing for the first timers to clearly know which parser to choose for babel when in astexplorer.  So I would recommend to rename it to `@babel/parser` to avoid any confusion.

**Expected behavior**
It should `@babel/parser` in parsers drop down.

**Additional context**
I would like to raise a PR.

**Comment by fkling** [comment]
Seems reasonable :slightly_smiling_face:
