### ISSUE TITLE
No longer possible to use `console.log` to help debugging transforms

### ISSUE THREAD

**Issue by patocallaghan** [fkling/astexplorer#517]
**Describe the bug**
While learning about ASTs and as a general debugging technique I will use `console.log` a lot to see what is going on. It seems you can no longer use `console.log` within your JS transforms to help debug them. 

**To Reproduce**
1. Go to https://astexplorer.net/#/gist/d4e1495d40f3b46cfda18ceedf39d156/a5ac2f579f70e3e4a9753c6f80ba969b0f411d3e
2. Open dev tools
3. make any edits to the source or transform js
4. A message says `Console was cleared`

**Expected behavior**
You expect to see `hello` in the console

**Browser (please complete the following information):**
 - OS: Catalina
 - Browser Chrome and Edge
 - Version 83

**astexplorer settings:**
- Selected parser: JavaScript but have also confirmed with CSS + post-css transforms
- Selected transformer (if applicable): jscodeshift

**Additional context**
It appears the console is being cleared from [this line](https://github.com/fkling/astexplorer/blob/164c4a8d27e4076029c1dbb8bdadd95d648efa23/website/src/store/transformerMiddleware.js#L75-L77) which was introduced in [this commit](https://github.com/fkling/astexplorer/commit/f739523c809760f2f31176a5998d56c6741f82a6) over the past few months

**Comment by hanford** [comment]
I was able to kind of resolve this by overwriting `console.clear` to a noop.

`console.clear = () => {}`

**Comment by fkling** [comment]
The console has been cleared [for the last 5 years](https://github.com/fkling/astexplorer/commit/9ebb75f520f931da28793e91a3b2dcf342bf744b#diff-7a430dc1ba2d3c46924f6e63acef437cR37). 

The reason for clearing the logs is to not be confused by errors from older invocations of the transform.

However, it seems that what the commit you pointed to did wrong is clearing the logs *after* the transform runs. It should be cleared *before* the transform runs.
