### ISSUE TITLE
@typescript-eslint/parser has stopped working

### ISSUE THREAD

**Issue by ecraig12345** [fkling/astexplorer#524]
**Describe the bug**
Viewing the AST generated by `@typescript-eslint/parser` is no longer possible. It worked a couple weeks ago.

**To Reproduce**
1. Go to https://astexplorer.net/
2. For the parser choose `@typescript-eslint/parser`
3. Observe that the tree doesn't update, and if you open the console there's an error loading the parser

**Expected behavior**
`@typescript-eslint/parser` loads and updates the tree

**Screenshots**
![image](https://user-images.githubusercontent.com/5864305/89331841-47921700-d647-11ea-870c-cd1d940ec5e3.png)

**Browser (please complete the following information):**
 - OS: Mac OS 10.15.5
 - Browser: Chrome
 - Version:  84.0.4147.89
(Also repros with any other browser and OS I tried, including in incognito mode to ensure there's not a problem with any cached stuff)

**astexplorer settings:**
- Selected parser: `@typescript-eslint/parser`
- Selected transformer (if applicable): none
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)
```
{
  "showTransformPanel": false,
  "parserSettings": {},
  "parserPerCategory": {
    "javascript": "acorn"
  },
  "workbench": {
    "parser": "acorn",
    "code": "/**\n * Paste or drop some JavaScript here and explore\n * the syntax tree created by chosen parser.\n * You can use all the cool new features from ES6\n * and even more. Enjoy!\n */\n\nlet tips = [\n  \"Click on any AST node with a '+' to expand it\",\n\n  \"Hovering over a node highlights the \\\n   corresponding location in the source code\",\n\n  \"Shift click on an AST node to expand the whole subtree\"\n];\n\nfunction printTips() {\n  tips.forEach((tip, i) => console.log(`Tip ${i}:` + tip));\n}\n",
    "keyMap": "default",
    "transform": {
      "code": "",
      "transformer": null
    }
  }
}
```

**Comment by fkling** [comment]
Does it work if you force refresh the page?

**Comment by bradzacher** [comment]
I tried an empty cache and hard reload in chrome - it throws the same error.
For good measure also tried in an incognito window - same error.

**Comment by fkling** [comment]
Looks like we are somehow replacing a module that some part of typescript-eslint depends on. I have tried to tweak the webpack configuration but haven't been successful yet. I'll keep trying.

**Comment by tosmolka** [comment]
+1, any updates on the issue? Thanks.

**Comment by ecraig12345** [comment]
If you're not having any luck debugging (or enough time to do it), would it be possible to roll back to the last working version for now?

**Comment by fkling** [comment]
It should work again as of d0d46179a0014ee2826d38cb81b9867de3fbfd0a (already deployed) . Please let me know if it doesn't.

**Comment by bradzacher** [comment]
For speed/size you could probably null out the entirety of `@typescript-eslint/experimental-utils/dist/ts-eslint`, as the parser doesn't use that codebase.

Though I'm not sure why it only just started breaking, as nothing in the parser actually consumes that particular file. I'd have thought webpack would do some tree-shaking... 🤷‍♂️ 

Note that with our upcoming [v4 release](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0-rc) you should be able to remove this workaround, as the parser will no longer rely on anything in the `experimental-utils` module.

**Comment by fkling** [comment]
Good to know @bradzacher, thank you!

**Comment by Olli-palkkaus** [comment]
I believe this bug has reappeared. 

Or did I misunderstand that it would have been fixed and deployed in https://astexplorer.net ? Or is this a different bug (same steps as above):

![image](https://user-images.githubusercontent.com/10129347/107636581-85669c80-6c75-11eb-852b-ebc98f58f3e1.png)

**Comment by fkling** [comment]
@Olli-palkkaus no, you were right, this bug resurfaced. Likely because a recent upgrade of another parser promoted the `globby` package to the top level `node_modules/` folder so that exclusion regex in the webpack config file didn't match anymore. This should be fixed now with https://github.com/fkling/astexplorer/commit/3df1b0f52f255fcb785cf4d7a05d078e747fdeb6 . You might have to force reload.
