### ISSUE TITLE
astexplorer.net not working

### ISSUE THREAD

**Issue by CyberAP** [fkling/astexplorer#537]
**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85

**Additional context**

The app fails to start, I get the following error in the console:

TypeError: Cannot read property 'category' of undefined

> vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2 TypeError: Cannot read property 'category' of undefined
>     at Function.mapStateToProps [as mapToProps] (app-c5eb03b169552eca11e7-27.js:1)
>     at mapToPropsProxy (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at Function.detectFactoryAndVerify (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at mapToPropsProxy (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at handleFirstCall (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at pureFinalPropsSelector (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2
>     at Object.useMemo (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at r.useMemo (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)
>     at ConnectFunction (vendors\~app-b7df4d39b9ca7fcb1cae-27.js:2)

I have tried hard refresh and it didn't help either.

**Comment by fkling** [comment]
Does it work in an incognito window?

**Comment by CyberAP** [comment]
Yes

**Comment by CyberAP** [comment]
After clearing site data it works, but that might be not obvious what to do for those who share the same issue with me.

**Comment by fkling** [comment]
Agreed. I will have to add something to make astexplorer more resilient when loading incompatible data from local storage. Would be interesting to know what data you had there but I guess it's too late now :wink:

**Comment by CyberAP** [comment]
I guess an outdated or removed parser might've been selected and then saved, and the app tried to use it at launch.
