### ISSUE TITLE
Time to rename repo?

### ISSUE THREAD

**Issue by RReverser** [fkling/astexplorer#54]
Since it's not just Esprima anymore, maybe it's worth to rename the repo to make it less confusing? Github takes care of redirects after renamings, so it should be harmless.

**Comment by fkling** [comment]
The problem is that it doesn't redirect gh-pages traffic. I.e. http://felix-kling.de/esprima_ast_explorer/ will break and somehow there are still people out there using that URL (#53).

**Comment by fkling** [comment]
But I could just put up another site there and mention that the page moved.

**Comment by RReverser** [comment]
Well... they can look into repo and go to new URL. Or you can set redirect from those URLs on own side.

**Comment by fkling** [comment]
If I create a repo again with the same name to notify that the page moved, the automatic redirects for all other GitHub stuff wouldn't work.... 

Being able to rename the repository was the reason why I got a dedicated domain :) But maybe we just have to wait a little longer...

**Comment by RReverser** [comment]
> If I create a repo again with the same name to notify that the page moved, the automatic redirects for all other GitHub stuff wouldn't work.... 

Oh, that's not what I suggested :) I just suggested to rename the repo and but redirect on side of `felix-kling.de` that would simply redirect `/esprima_ast_explorer` -> `http://astexplorer.net/`.

**Comment by fkling** [comment]
Ah... `felix-fkling.de` is also just a GH page. I guess I could create a page with that name there and say that it moved.

**Comment by fkling** [comment]
Renamed! I added a redirect from http://felix-kling.de/esprima_ast_explorer : https://github.com/fkling/fkling.github.com/blob/master/esprima_ast_explorer/index.html .

**Comment by RReverser** [comment]
Yay! I just thought that name becomes even less relevant with multiple langs.

**Comment by fkling** [comment]
Definitely, and I wanted to do that sooner or later anyway. Getting a TLD was the first step.
