### ISSUE TITLE
[Feature request] Hope update Typescript version to 4.0

### ISSUE THREAD

**Issue by echoloyuk** [fkling/astexplorer#540]
Hello, everybody, I feels so happy to use AST explorer, and highly hope for update typescript version to 4.0.x. One of difference is the syntaxKind enum number. In TS 4.0, more syntax kind being imported, and 3.8.3 will have the incorrect kind number.

**Comment by fkling** [comment]
Typescript is now updated to v4!

**Comment by echoloyuk** [comment]
> Typescript is now updated to v4!

Great! Thank you! So happppy to see that!

**Comment by alber70g** [comment]
Would it be possible to select a specific version?
