### ISSUE TITLE
Modify decoratorsBeforeExport to true

### ISSUE THREAD

**Issue by sangm** [fkling/astexplorer#565]
Hi,

I'm working on a project where I require this option to be _true_. 
Seeking to understand, what's the cost of changing this flag to true in babylon parser? (https://github.com/fkling/astexplorer/blob/d2bf1620c9efe02866650de60cad63130ce7246d/website/src/parsers/js/transformers/babel7/index.js#L37)

**Comment by fkling** [comment]
Sorry for letting this slip through. 

That's currently a limitation of how transformers are integrated into astexplorer: They cannot have configurable settings.

I think your best bet for the time being is to run a copy of astexplorer and change that flag locally.
