### ISSUE TITLE
@typescript-eslint/parser not working

### ISSUE THREAD

**Issue by jkennedy1980** [fkling/astexplorer#567]
**Describe the bug**
The UI won't produce an AST for Typescript Eslint. It was working a few days ago.

**To Reproduce**
1. Go to the web page
2. Change the ast type to `@typescript-eslint/parser`
3. Paste in any typescript code
4. Observe that the UI does not show an AST and that there are errors in the console.

**Expected behavior**
The AST should be displayed in the right pane.

**Screenshots**
![image](https://user-images.githubusercontent.com/571879/107807556-278d8f80-6d1d-11eb-9b89-529667dad1e9.png)

**Browser (please complete the following information):**
 - OS: MacOS
 - Tested in Chrome and Safari - same behavior
 - Chrome: 88.0.4324.150, Safari: 14.0.3 (16610.4.3.1.4)

**astexplorer settings:**
- Selected parser: @typescript-eslint/parser
- Selected transformer: n/a
- Contents of the local storage key:
```json
{"showTransformPanel":false,"parserSettings":{},"parserPerCategory":{"javascript":"@typescript-eslint/parser"},"workbench":{"parser":"@typescript-eslint/parser","code":"import { Required } from '@general-galactic/entity-decorators'\n\nexport default class CreateDataStreamEventV1 {\n\n    // TODO: make this more specific with broken out fields later\n    @Required\n    eventData: Record<string, unknown>\n\n    constructor(json?: Record<string, any>) {\n        if( !json ) return\n        this.eventData = json\n    }\n\n}\n","keyMap":"default","transform":{"code":"","transformer":null}}}
```

**Comment by fkling** [comment]
It should work again now. You might have to force reload.
