### ISSUE TITLE
import('./types').Foo cannot be compiled

### ISSUE THREAD

**Issue by eps1lon** [fkling/astexplorer#575]
**Describe the bug**
`type C = import('./').A;` is not accepted by `@babel/parser` (but typescript and `@typescript-eslint`

**To Reproduce**
1. Go to https://astexplorer.net/#/gist/143946b2cd5eed110dfefb1713fd3a75/b6f44073bca560837d7f5bc7e3c81509486a2108

**Expected behavior**
Syntax is accepted.

**Screenshots**
![Screenshot from 2021-03-27 11-11-13](https://user-images.githubusercontent.com/12292047/112717463-2f7c4a00-8eed-11eb-9dcd-53e9e3d7bb26.png)

**Browser (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 89

**astexplorer settings:**
- Selected parser: `@babel/parser`
- Selected transformer (if applicable): `babelv7`

**Additional context**
Syntax is accepted by typescript and `@typescript-eslint` parsers. [It's valid TypeScript](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=5&pc=25#code/JYWwDg9gTgLgBDAnmApnA3nAgnAvnAMyghDgHIA6AejIChalU4AhOAXmwG57G0BhdnFCRYACko0AlBSycgA).

**Comment by fkling** [comment]
You have to enable typescript support in the parser settings. Click on the gear icon next to the parser name to do that.

**Comment by eps1lon** [comment]
> You have to enable typescript support in the parser settings. Click on the gear icon next to the parser name to do that.

@fkling  There is no such option for @typescript-eslint/parser

**Comment by fkling** [comment]
Oh, I was only focusing on the *parser*, not the *transformer*. If you are using babel as transformer then it's not possible to enable typescript support atm. So it's the same problem as in your other issue.

**Comment by eps1lon** [comment]
> Oh, I was only focusing on the parser, not the transformer. If you are using babel as transformer then it's not possible to enable typescript support atm. So it's the same problem as in your other issue.

I don't want to use babel as a transformer but eslint. Which produces the same error: https://astexplorer.net/#/gist/9374cd3e1f7fe73ce87980a4fc2dcb21/e67c62f7244f16a034d89844f20d5cc98444eca9
