### ISSUE TITLE
Feature Request: Description of code segments

### ISSUE THREAD

**Issue by codinghusi** [fkling/astexplorer#576]
Hey there, just got a little idea:
sometimes when I learn a new programming language, I don't understand all parts in code examples.
I'd find it pretty neat, if I could hover over code segments and get a description of what those do.
Does something like that fit into this project?

Have a nice day :)

**Comment by fkling** [comment]
It's a good idea :) But I don't think astexplorer is the right place for this. I'm a fan of tools doing "one thing well". I see astexplorer as something that could enable *building* such a tool. I have actually started to prototype something like this for JavaScript, and if the related code/framework ever gets completed it could also be used for other programming languages: https://felix-kling.de/explainjs

**Comment by codinghusi** [comment]
Okay you're right. I fully agree with you!
Is your project 'explainjs' opensource?

**Comment by fkling** [comment]
I haven't published the code yet but I guess I should despite it not being finished yet. I'll write up a readme and create a repo in the next couple of days.
