### ISSUE TITLE
htmlparser2 add comment but get error

### ISSUE THREAD

**Issue by felaofan** [fkling/astexplorer#577]
**Describe the bug**
When i use htmlparser2 to parse html with the [demo](https://astexplorer.net/#/2AmVrGuGVJ), i add a comment to the html, but the parser throw "Cannot set property 'endIndex' of undefined", what should i do?

**Screenshots**
Here is my code
``` html
<!DOCTYPE html>
<html lang=en>
<body>
    <!-- comment test -->
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
</body>
</html>
```

**Comment by fkling** [comment]
Mmh, looks like this line might cause the issue?

https://github.com/fkling/astexplorer/blob/bac2c92fe93337b0a2906678ee50bf9c2c0dbd40/website/src/parsers/html/htmlparser2.js#L28

Not sure how htmlparser2 represents comment nodes. I guess it would have to be adjusted for that.
