### ISSUE TITLE
Better options in vue-eslint-parser

### ISSUE THREAD

**Issue by muxishuihan** [fkling/astexplorer#582]
Hi~ 
In default options, vue-eslint-parser can't deal with "?." and it will cause an"Unexpected token ." error.
`let arr = res?.data?.list`
is equals to 
`let arr = res && res.data && res.data.list`

It may be better if we add "ecmaVersion": 2020" in the option of vue-eslint-parser(vue-eslint-parser.js) module.
Best wishes.

**Comment by fkling** [comment]
Mmh, it doesn't look like to make a difference. If I set it to 2021 I still get a parser error. But maybe the version and/or dependencies need to be updated.

**Comment by fkling** [comment]
This should work now. https://github.com/fkling/astexplorer/commit/4a903b476ad4cbffa6dff72c9d9a2f4bb944c987
