### ISSUE TITLE
[Feature Request]: Decouple CodeMirror mode from id or category

### ISSUE THREAD

**Issue by tomsfernandez** [fkling/astexplorer#597]
Hi! I am  trying to define a category for the RAML API Specification which is syntax is based on YAML. It doesn't fit into the YAML category as the resulting AST has api specification concepts.

Specifically I'm having trouble applying the YAML code mirror syntax coloring to the example code in the code editor. After a fast check I saw that the editor mode is decided by the id field of the parser or the name of the category, 2 things that are different from YAML.

Codemirror doesn't have a configuration specific for RAML as it is YAML with specific domain concepts.

Would it be much work to add the possibility to override this criteria for choosing the syntax coloring by adding the chosen colors as an option in the categories index.js file?

An example RAML:

```yaml
#%RAML 1.0
title: Mobile Order API
baseUri: http://localhost:8081/api
version: 1.0

uses:
  assets: assets.lib.raml

annotationTypes:
  monitoringInterval:
    type: integer

/orders:
  displayName: Orders
  get:
    is: [ assets.paging ]
    (monitoringInterval): 30
    description: Lists all orders of a specific user
    queryParameters:
      userId:
        type: string
        description: use to query all orders of a user
  post:
  /{orderId}:
    get:
      responses:
        200:
          body:
```

**Comment by tomsfernandez** [comment]
P.D.: I can try to make the change if the change is correct.

**Comment by fkling** [comment]
You should be able to set the mode by setting `editorMode` in the category: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/fkling/astexplorer%24+editorMode&patternType=literal

**Comment by tomsfernandez** [comment]
Nice, thanks!
