### ISSUE TITLE
Transforms can't work with decorators

### ISSUE THREAD

**Issue by runspired** [fkling/astexplorer#626]
This is roughly similar to #36 except that the stage-0 setting isn't enough.

If using some code with a decorator and using the jscodeshift transform, the following error is encountered:

```
This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (2:2)
```

**Comment by fkling** [comment]
Looks like decorators are enabled for the [`babylon` parser](https://github.com/facebook/jscodeshift/blob/25f0c6f234429a1d1853e8a759ffcfdc6c4b1655/parser/babylon.js#L29).

You can tell jscodeshift to use this parser by setting

```
export const parser = 'babylon';
```
