### ISSUE TITLE
context.getPhysicalFilename is not a function

### ISSUE THREAD

**Issue by AlexJeffcott** [fkling/astexplorer#627]
**Describe the bug**
context.getPhysicalFilename() results in context.getPhysicalFilename is not a function despite its being [released in eslint v7.28.0](https://eslint.org/blog/2021/06/eslint-v7.28.0-released)

**To Reproduce**
1. Go to 'https://astexplorer.net/#/gist/4773c47aa107be0e924ffdd656fc6bcd/839c14a9125bf73dc3b4f2c4916693ff98127bdd'

**Expected behavior**
Should not cause an error

**Screenshots**
![image](https://user-images.githubusercontent.com/9036846/148234857-175d1ab0-dab6-45d4-a7b5-e130c5878388.png)

**Browser (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 96

**astexplorer settings:**
- Selected parser: babel-eslint9
- Selected transformer (if applicable): Eslint 4
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)
{"showTransformPanel":true,"parserSettings":{},"parserPerCategory":{"javascript":"babel-eslint9"},"workbench":{"parser":"babel-eslint9","code":"import {hello} from 'world'","keyMap":"default","transform":{"code":"export default function(context) {\\n  return {\\n      ImportDeclaration(node) {\\n        const filePath = context.getPhysicalFilename()\\n      }\\n  };\\n};\\n","transformer":"eslint-v4"}}}
**Additional context**

**Comment by fkling** [comment]
If the function was added in eslint v7 then it's not surprising it doesn't work with eslint v4. Nobody has added support for the latest eslint version yet. It might be as simple as duplicating the v4 wrapper but it could also be more difficult depending on how much the API changed.
Feel free to open a new issue (or a PR) for adding support for eslint v8.
