### ISSUE TITLE
URL for special language

### ISSUE THREAD

**Issue by ai** [fkling/astexplorer#67]
Maybe we should have some shortcut to enable features. Like if you go to `http://astexplorer.net/#postcss` it will enable CSS and PostCSS.

**Comment by RReverser** [comment]
That would be cool indeed. For now, hashes are used for combination of source code + parser, so as workaround you can just `Save` your snippet with PostCSS parser being chosen and share the URL you get, like: http://astexplorer.net/#/np0DfVT78g

**Comment by ai** [comment]
Awesome. Thanks for quick solution

**Comment by ai** [comment]
Techincally I am OK with it

**Comment by fkling** [comment]
That's basically what I wanted to do in #55.

**Comment by ai** [comment]
Oops, sorry for duplicate
