### ISSUE TITLE
in the website/，`npm run watch` cannot observe the change of files

### ISSUE THREAD

**Issue by raintoway** [fkling/astexplorer#671]
**Describe the bug**
in the website/，`npm run watch` cannot observe the change of files

**To Reproduce**
1. Go to website/
2. npm i 
3. npm run start
4. npm run watch
5. open the browser，visite the `http://127.0.0.1:8080`
6. change the source file
7. refresh browser，can not view the change of relative file

**Expected behavior**
refresh browser，can view the change of relative file

**Screenshots**

**Browser (please complete the following information):**

**astexplorer settings:**
- Selected parser: [e.g. acorn]
- Selected transformer (if applicable): [e.g. jscodeshift]
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)

**Additional context**

**Comment by raintoway** [comment]
because u don't check the 'Disable cache' option of browser，the app.js will be reload from browser's cache instead of network which is new

**Comment by fkling** [comment]
How are you serving the files? I.e. which webserver are you using? It should work with `yarn start`/`npm run start`. It uses the `serve` module which sets etags and properly "invalidates" a file (I just tested it).

**Comment by raintoway** [comment]
> How are you serving the files? I.e. which webserver are you using? It should work with `yarn start`/`npm run start`. It uses the `serve` module which sets etags and properly "无效" a file (I just tested it).

1. Go to website/
2. npm i 
3. npm run start
4. npm run watch
5. open the browser，visite the `http://127.0.0.1:8080`
6. change the source file
7. refresh browser，can not view the change of relative file

**Comment by fkling** [comment]
Mmh, probably can't help you there since it works for me. Since there is a workaround by disabling caching files I'm going to close this.
In the long run the way how development works is probably going to change anyway.
