### ISSUE TITLE
Issue with removing the transform panes when switching

### ISSUE THREAD

**Issue by hzoo** [fkling/astexplorer#68]
When you switch between languages, should the transform change automatically (ex: after switching from js/babel to html, the babel transform pane is still there). In the case of switching to html the pane stays on the screen even though the transform toggle is disabled.

**Comment by RReverser** [comment]
That's what I was talking about in https://github.com/fkling/astexplorer/pull/62#issuecomment-162333611 :disappointed:

**Comment by RReverser** [comment]
If you can fix it, that would be awesome.

**Comment by RReverser** [comment]
@fkling Awesome, thank you!
