### ISSUE TITLE
Website freezes if Java Parser is selected with JSON view tab

### ISSUE THREAD

**Issue by anuragkr22** [fkling/astexplorer#706]
**Describe the bug**
After selecting 'Java' as the parser, clicking on the 'JSON' tab view tab freezes the page for 5-10 seconds. After this an error message occurs showing 'the page isn't responding'. If the page does respond, it again freezes frequently while doing so. Sometimes error occurs like 'This page is having a problem'.

**To Reproduce**
1. Go to 'https://astexplorer.net/'
2. Click on 'Java'
3. Click on 'JSON'
4. The page freezes

**Expected behavior**
The page should have worked normally without much interruptions and freezing.

**Screenshots**
![Screenshot 2024-01-06 195259](https://github.com/fkling/astexplorer/assets/62297542/98f2c672-9dd4-4451-8285-99af23fbf217)
![Screenshot 2024-01-06 195516](https://github.com/fkling/astexplorer/assets/62297542/bdc94a6d-1864-4bc2-a79c-99790e29dcd6)

**Browser (please complete the following information):**
 - OS: [Windows 11 Home Single Language]
 - Browser [Edge]
 - Version [120.0.2210.121 (Official build) (64-bit)]

**astexplorer settings:**
- Selected parser: java-parser-2.0.1
- Selected transformer (if applicable): not applicable
- Contents of the local storage key `explorerSettingsV1` (code can be removed if you don't want it to be public)
{showTransformPanel: false,
parserSettings: {}
parserPerCategory : {}
parserSettings : {}
showTransformPanel : false
workbench : {parser: "java-parser",…}
code :```
 "package example;
import java.util.ArrayList;
import java.util.List;
public class Example {
private ArrayList<String> names;
public Example() {
names = new ArrayList<>();
}
public void addName(String name) {
names.add(name);
}
public List<String> getNames() {
return new ArrayList<>(names);
}
}"
```
keyMap : "default"
parser : "java-parser"
transform : {code: "", transformer: null}
        

**Additional context**
Add any other context about the problem here.

**Comment by Scipion** [comment]
With enough memory (and patience) you can see that parsing the key _START_CHARS_HINT_ contains hundreds of thousands of characters and it's accessible in several places, so stringifying it produces a hundreds of Megs string.

The stringify happens in a generic component so it doesn't seems trivial a patch here, cause it can affect other parses.
