### ISSUE TITLE
Change placement of parser information

### ISSUE THREAD

**Issue by fkling** [fkling/astexplorer#72]
The toolbar is now so wide that parser information is not always shown properly on narrow screens. This is from a 13" screen:

![screen shot 2015-12-08 at 10 33 05 am](https://cloud.githubusercontent.com/assets/179026/11664528/25e487d4-9d97-11e5-8883-3f45b4647714.png)

Any suggestions for how/where to put this? Or should we simply break on white space?

**Comment by RReverser** [comment]
Oh, never saw this. I guess we can just remove the acorn-jsx part from here, and other parsers have shorter information by default.

**Comment by fkling** [comment]
That would also be an option :) We might still run in this problem later though...

**Comment by RReverser** [comment]
Alternatively, we can put "parser info" button here that would show popup with details :)

**Comment by giuseppeg** [comment]
+1
How about this

<img width="1550" alt="screenshot 2016-02-20 13 27 19" src="https://cloud.githubusercontent.com/assets/711311/13199276/c7763b4c-d7d5-11e5-95ff-fac66f7668fe.png">

left:top -> codemod
left:bottom -> result (output)
right:top -> source
right:bottom -> AST explorer

**Comment by fkling** [comment]
I removed the JSX plugin information from the parser info, so this is a non-issue (for) now.
