### ISSUE TITLE
Unable to set sourceType in parser settings to script in babylon6

### ISSUE THREAD

**Issue by udnisap** [fkling/astexplorer#81]
I am trying on http://astexplorer.net/#/ijSdoepnJz/1

**Comment by RReverser** [comment]
@udnisap @fkling There is a mistype here: https://github.com/fkling/astexplorer/blob/master/src/parsers/js/babylon6.js#L75 should be `value` not `vaue`

**Comment by udnisap** [comment]
Good catch @RReverser.
