### ISSUE TITLE
Explorer hangs sometimes, could be related to source map support

### ISSUE THREAD

**Issue by fkling** [fkling/astexplorer#82]
Example: http://astexplorer.net/#/ijSdoepnJz/1 , cc @RReverser

**Comment by RReverser** [comment]
Hmm, this is weird. Could it be somehow related to `debugger` statement? It hung my browser, but when I opened the link with devtools and quickly clicked "resume" on each `debugger` hit, it worked.

**Comment by fkling** [comment]
It starts hanging once I hover over the AST, even without `debugger` statement.

**Comment by fkling** [comment]
The infinite loop is her: https://github.com/fkling/astexplorer/blob/master/src/TransformOutput.js#L108-L111 . `lineStart` stays `0`.

**Comment by RReverser** [comment]
Oh. But... how can it stay there?

**Comment by fkling** [comment]
`src.lastIndexOf('\n', -1)` keeps returning `0`

**Comment by RReverser** [comment]
That's pretty weird, it should return `-1` because nothing is found before position `-1`.

**Comment by RReverser** [comment]
E.g. `'123,456,789'.lastIndexOf(',', -1)` does return `-1` as expected.

**Comment by fkling** [comment]
`','.lastIndexOf(',', -1)` returns `0`, in both Chrome and Firefox...

**Comment by fkling** [comment]
Ah:

> Let start be min(max(pos, 0), len).

http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.lastindexof

**Comment by RReverser** [comment]
Hmm, so `-1` gets automatically upgraded to `0`. Damn, I feel ashamed - #idontknowjs :)

**Comment by fkling** [comment]
:D I blame MDN:

>  If fromIndex < 0,  the string is not searched and -1 is returned.

**Comment by RReverser** [comment]
Fixed MDN page so that others wouldn't be caught by it :)

**Comment by RReverser** [comment]
@fkling Will you fix it or do you want me to PR?

**Comment by fkling** [comment]
I'll fix it. Changing the condition to `> 0` should suffice, right?

**Comment by fkling** [comment]
Or not... that doesn't seem to work.

**Comment by fkling** [comment]
I mean, it works without leading empty lines.... not sure how empty lines are treated in source maps.

**Comment by RReverser** [comment]
No, it requires either `break` if `lineStart === 0` in the loop or `if` + `do-while` with `> 0`.

**Comment by RReverser** [comment]
Empty lines should be still counted, but stop at the very beginning of string.

**Comment by fkling** [comment]
Even with the `if` statement, this doesn't seem right:
![screen shot 2015-12-12 at 11 33 42 am](https://cloud.githubusercontent.com/assets/179026/11763547/423f6c48-a0c4-11e5-93c6-68b2fb39ac5a.png)

**Comment by RReverser** [comment]
How did you do it? Can you show me a snippet?

**Comment by fkling** [comment]
```js
    while (lineStart >= 0) {
      lineStart = src.lastIndexOf('\n', lineStart - 1);
      line++;
      if (lineStart === 0) {
        break;
      }
    }
```

**Comment by RReverser** [comment]
Yeah, off-by-one. How about this?

```javascript
let lineStart = src.lastIndexOf('\n', pos - 1);
let column = pos - lineStart - 1;
let line = 1;
while (lineStart > 0) {
  lineStart = src.lastIndexOf('\n', lineStart - 1);
  line++;
}
if (lineStart === 0) {
	line++;
}
```

**Comment by RReverser** [comment]
(basically the same as adding `line++` before `break`)

**Comment by fkling** [comment]
Yep, works. Thanks!
