### ISSUE TITLE
Shows errors for valid jscodeshift transform

### ISSUE THREAD

**Issue by vramana** [fkling/astexplorer#88]
Hi,

Thanks for this amazing tool.

[This transform](http://astexplorer.net/#/ZS1RwQm1oy) is passing tests on my machine locally. But I get this error `Cannot read property 'node' of undefined` in astexplorer. This is my [original repo](https://github.com/vramana/ember-codemod) and the transform is `initializer-arity`. 

Sometime missing a semicolon at the end of statement seems to trigger similar kind of errors. Here is reproducable [example](http://astexplorer.net/#/sC2pNUfG3T) And the semicolon is missing for the statement `root.find(j.FunctionDeclaration, ...)....`.

**Comment by fkling** [comment]
This seems to be an issue with how https://github.com/ForbesLindesay/halting-problem instruments the code. Will look into this a bit more.

**Comment by fkling** [comment]
Filed an issue: ForbesLindesay/halting-problem/issues/2. In the meantime, if you use semicolons everywhere, especially before function calls, there shouldn't be an issue: http://astexplorer.net/#/T9o70FCwaf

**Comment by fkling** [comment]
Updated halting-problem.
