### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vitaly-t** [fkling/astexplorer#91]
This project is a nice playground for all those parsers. Thank you for making this!

I believe that for most people who stumble upon it, we are trying to find the best AST parser for our specific tasks.

And as far as the decision-making goes, your project is missing some key information that would simplify things for a researcher.

I understand you want your project to stay neutral about all the existing AST projects, but at least some basic statistics would have been really helpful:

* Performance charts
* Memory consumption charts
* Level of support for ES5, ES6, ES7
* Tree-Navigation features, performance

Not only this would be a great help to those who is trying to make the best pick among AST parsers, but also for the developers of AST projects to be able to see where their project has weaknesses.

**Comment by RReverser** [comment]
Well, as for the performance stats - I believe they are not really fair in such context given that we run transpiled, pre-bundled code in browser whilst it's usually executed in Node.js environment and numbers might differ heavily. Also, it heavily depends on the input, configuration of each parser etc., and thus I always prefer people running benchmarks on their real environment and input rather than some abstract microbenchmarking numbers that don't tell much useful information.

**Comment by vitaly-t** [comment]
Well, at least esprima authors didn't think so, so they did this: http://esprima.org/test/compare.html

I'm sure there other benchmarks out there provided by other AST parsers.

I thought it would be good to have a central benchmark for them all, and this project, being an independent one is the best place for that.

**Comment by RReverser** [comment]
> I'm sure there are other benchmarks out there provided by other AST parsers.

Of course - we at Acorn do the same, but again - it's just benchmarks for browsers and with preset configurations. They never show real performance on real input with real options :) (e.g. source maps toggles, feature toggles, error tracking etc.)

**Comment by fkling** [comment]
If someone wants to write a benchmark script and/or feature detection script to collect these metrics, based on astexplorer, I'm happy to accept it or take a look at it, but I won't have time to do something like this myself.

Closing this for now since there is nothing actionable for me...
