### ISSUE TITLE
Add inline documentation for ast-type constructors

### ISSUE THREAD

**Issue by vjeux** [fkling/astexplorer#92]
I've been thinking about how to best document jscodeshift and i think that having auto-complete/typeahead inside of astexplorer.net would be huge.

My biggest annoyance when writing codemods is that I want to create a node of type Something
but i don't know what arguments it takes.

Being able to do `t.something(<list of arguments from ast-types>)` would be great or, maybe at the bottom of the screen, when you select t.something, it shows the type definition.

**Comment by fkling** [comment]
I like the idea. I think it should be relatively easy for builder methods, since we can compile the list beforehand.

Not sure how much we can do for autocompletion for collections, since that partially depends on the context / runtime information.

**Comment by vjeux** [comment]
I think that just a hardcoded pass that looks for j.[a-zA-Z]+(...) would be enough, no need to get fancy with flow or anything :)

**Comment by RReverser** [comment]
> Not sure how much we can do for autocompletion for collections, since that partially depends on the context / runtime information.

We could inject Tern in order to do this http://ternjs.net/doc/demo/#simple

**Comment by fkling** [comment]
Oh right, almost forgot about tern.

**Comment by fkling** [comment]
Although, tern seems to require a server? I'll look more into it eventually (help is always welcome too ;) )

**Comment by RReverser** [comment]
No, it runs completely locally.

> help is always welcome too ;)

Like I didn't before :P Just need to get rid of at least half of parallel post-festive-period projects at work (I'm trying :) ).

**Comment by fkling** [comment]
> No, it runs completely locally.

I mean, I'm wondering if it can run in the browser. I just skimmed over the beginning (http://ternjs.net/doc/manual.html#server), so I'm probably missing all the stuff relevant for me.

> Like I didn't before :P

My statement was directed at everybody reading this issue, not you specifically ;)

**Comment by RReverser** [comment]
> I mean, I'm wondering if it can run in the browser. I just skimmed over the beginning (http://ternjs.net/doc/manual.html#server), so I'm probably missing all the stuff relevant for me.

Yeah - that's why I've sent demo which runs in the browser (you can see from network tab that nothing is served). I believe it's just browserified server on the client-side, although don't remember exactly too, never did it.

**Comment by fkling** [comment]
Oh man, I missed that link..... :-/ Sorry.

**Comment by fkling** [comment]
I'm kind of getting there:

<img width="689" alt="screen shot 2016-01-15 at 6 51 46 pm" src="https://cloud.githubusercontent.com/assets/179026/12368403/2584cc14-bbb9-11e5-9efd-750d1ea855c5.png">
<img width="730" alt="screen shot 2016-01-15 at 6 51 57 pm" src="https://cloud.githubusercontent.com/assets/179026/12368406/287251b2-bbb9-11e5-8ce1-37b8b1ab0c15.png">


It's a bit hacky, but it works. My plan is to partially generate the API definition from `ast-types` (lets see how much is possible here), and manually define the default Collection API methods.

**Comment by RReverser** [comment]
@fkling I guess you can start with defs from this PR to ast-types https://github.com/jamestalmage/ast-types/blob/typescript-def/ts/def/generated.d.ts#L869-L1303, combine with our official ESTree definitions https://github.com/estree/formal/blob/master/formal-data/typescript/es6.d.ts and convert into Tern's.

**Comment by vjeux** [comment]
You can also execute all the functions with an invalid argument and parse the exception which had the argument types it expects

**Comment by RReverser** [comment]
> You can also execute all the functions with an invalid argument and parse the exception which had the argument types it expects

That's less descriptive (at least in the way it doesn't specify AST node properties and so).

**Comment by RReverser** [comment]
Tern has built-in tool for conversion from TypeScript defs http://ternjs.net/doc/manual.html#utils, so it should be fairly easy to concatenate pieces from those two files and pass into it :)

**Comment by fkling** [comment]
I ended up writing my own short script to generate the definition directly from `ast-types`. While it would have been nice to use the TS files, I believe the ast-types ones are already outdated. This way I can also customize the doc strings.

I'm basically done for now, just need to cleanup the code a little:

![autocomplete](https://cloud.githubusercontent.com/assets/179026/12370727/ec6dc256-bbe9-11e5-9c39-4836b784113c.gif)

**Comment by vjeux** [comment]
You did not lie! You did it before the end of the day! This is so exciting!

**Comment by RReverser** [comment]
Yay, looks awesome!

**Comment by iamdustan** [comment]
:exclamation: :exclamation: this is soooo awesome.

**Comment by fkling** [comment]
Sorry for the long radio silence on this issue. I was just pretty busy.

I pushed the changes to a new branch: https://github.com/fkling/astexplorer/tree/auto-complete

There is one big issue: In some cases, acorn's loose mode will lock up the browser. Unfortunately I cannot reproduce this with standalone acorn. One example where the browser locks up is

```javascript
export default function transformer(file, api) {
  foo('
};
```

, just after typing the opening quote (`'`).  Pausing the execution reveals that acorn is trying to read tokens, but for some reason their `start` and `end` positions are `NaN`, bringing the parser in an infinite loop.

Until this is resolved, I can't merge this. I will investigate more, but I'm hoping @RReverser can help out too :)

**Comment by RReverser** [comment]
> Unfortunately I cannot reproduce this with standalone acorn.

Interesting. Maybe outdated version of Acorn somewhere if you cannot reproduce it locally? Cannot reproduce online at http://ternjs.net/doc/demo/#simple neither.

**Comment by fkling** [comment]
> Maybe outdated version of Acorn somewhere if you cannot reproduce it locally?

I don't think so, I updated acorn.

**Comment by RReverser** [comment]
Sure, and as you said, you cannot reproduce with updated Acorn (3.0.0), right?

While Tern 0.17.0 which is also in dependencies, seems to rely on `acorn: "^2.7.0"` according to `npm view`, and IIUC, you're having this lockup in Tern - is that correct?

**Comment by fkling** [comment]
Yeah, but tern doesn't use its version of acorn (that doesn't work because the way it `require`s it), it uses the global version that I am loading.

Anyway, I just did a pull and fresh install on my other computer and it works fine there. So it indeed seems to be some strange issue with my dependencies.

I will do a fresh install on my laptop and see if the problem goes away :) Sorry for the trouble!

**Comment by RReverser** [comment]
Np - let me know if that doesn't work.

**Comment by RReverser** [comment]
\o/
